// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// Defines values for JobStatus.
const (
	Failed  JobStatus = "failed"
	Skipped JobStatus = "skipped"
	Success JobStatus = "success"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Skipped:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// AgentCreateRequest defines model for AgentCreateRequest.
type AgentCreateRequest struct {
	Metadata *ServerMetadata `json:"metadata,omitempty"`
	Name     string          `json:"name"`
	Type     *string         `json:"type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Server defines model for Server.
type Server struct {
	Hostname        string         `json:"hostname"`
	Hypervisor      string         `json:"hypervisor"`
	Id              UUID           `json:"id"`
	Location        string         `json:"location"`
	Metadata        ServerMetadata `json:"metadata"`
	OperatingSystem string         `json:"operating_system"`
}

// ServerCreateRequest defines model for ServerCreateRequest.
type ServerCreateRequest struct {
	AgentIds        *[]UUID               `json:"agent_ids,omitempty"`
	Agents          *[]AgentCreateRequest `json:"agents,omitempty"`
	Hostname        string                `json:"hostname"`
	Hypervisor      *string               `json:"hypervisor,omitempty"`
	Location        *string               `json:"location,omitempty"`
	Metadata        *ServerMetadata       `json:"metadata,omitempty"`
	OperatingSystem *string               `json:"operating_system,omitempty"`
}

// ServerDataResponse defines model for ServerDataResponse.
type ServerDataResponse struct {
	Data Server `json:"data"`
}

// ServerJobAssociateRequest defines model for ServerJobAssociateRequest.
type ServerJobAssociateRequest struct {
	AutomationId UUID   `json:"automation_id"`
	JobId        string `json:"job_id"`
}

// ServerJobAssociation defines model for ServerJobAssociation.
type ServerJobAssociation struct {
	Automation   string    `json:"automation"`
	AutomationId UUID      `json:"automation_id"`
	JobId        string    `json:"job_id"`
	Location     string    `json:"location"`
	Provider     string    `json:"provider"`
	Status       JobStatus `json:"status"`
	Url          URL       `json:"url"`
}

// ServerJobListResponse defines model for ServerJobListResponse.
type ServerJobListResponse struct {
	Data       []ServerJobAssociation `json:"data"`
	Pagination Pagination             `json:"pagination"`
}

// ServerListItem defines model for ServerListItem.
type ServerListItem struct {
	Compliant       bool                  `json:"compliant"`
	Hostname        string                `json:"hostname"`
	Hypervisor      string                `json:"hypervisor"`
	Id              UUID                  `json:"id"`
	Location        string                `json:"location"`
	Metadata        ServerMetadata        `json:"metadata"`
	OperatingSystem string                `json:"operating_system"`
	Relations       ServerRelationSummary `json:"relations"`
}

// ServerListResponse defines model for ServerListResponse.
type ServerListResponse struct {
	Data       []ServerListItem `json:"data"`
	Pagination Pagination       `json:"pagination"`
}

// ServerMetadata defines model for ServerMetadata.
type ServerMetadata = map[string]interface{}

// ServerRelationSummary defines model for ServerRelationSummary.
type ServerRelationSummary struct {
	AgentCount   int `json:"agent_count"`
	JobCount     int `json:"job_count"`
	ReleaseCount int `json:"release_count"`
}

// ServerReleaseAssociateRequest defines model for ServerReleaseAssociateRequest.
type ServerReleaseAssociateRequest struct {
	ApplicationId UUID `json:"application_id"`
	ReleaseId     UUID `json:"release_id"`
}

// ServerReleaseAssociation defines model for ServerReleaseAssociation.
type ServerReleaseAssociation struct {
	Application   string `json:"application"`
	ApplicationId UUID   `json:"application_id"`
	Branch        string `json:"branch"`
	CommitSha     string `json:"commit_sha"`
	ReleaseId     UUID   `json:"release_id"`
	Version       string `json:"version"`
}

// ServerReleaseListResponse defines model for ServerReleaseListResponse.
type ServerReleaseListResponse struct {
	Data       []ServerReleaseAssociation `json:"data"`
	Pagination Pagination                 `json:"pagination"`
}

// ServerUpdateRequest defines model for ServerUpdateRequest.
type ServerUpdateRequest struct {
	AgentIds *[]UUID               `json:"agent_ids,omitempty"`
	Agents   *[]AgentCreateRequest `json:"agents,omitempty"`
}

// ServerWithRelations defines model for ServerWithRelations.
type ServerWithRelations struct {
	Hostname        string                `json:"hostname"`
	Hypervisor      string                `json:"hypervisor"`
	Id              UUID                  `json:"id"`
	Location        string                `json:"location"`
	Metadata        ServerMetadata        `json:"metadata"`
	OperatingSystem string                `json:"operating_system"`
	Relations       ServerRelationSummary `json:"relations"`
}

// ServerWithRelationsDataResponse defines model for ServerWithRelationsDataResponse.
type ServerWithRelationsDataResponse struct {
	Data ServerWithRelations `json:"data"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// JobID defines model for JobID.
type JobID = string

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// ServerIDPath defines model for ServerIDPath.
type ServerIDPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListServersParams defines parameters for ListServers.
type ListServersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// AgentId Return only servers where the given agent is installed
	AgentId *UUID `form:"agent_id,omitempty" json:"agent_id,omitempty"`
}

// ListServerJobsParams defines parameters for ListServerJobs.
type ListServerJobsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// DissociateServerJobParams defines parameters for DissociateServerJob.
type DissociateServerJobParams struct {
	AutomationId UUID `form:"automation_id" json:"automation_id"`
}

// ListServerReleasesParams defines parameters for ListServerReleases.
type ListServerReleasesParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = ServerCreateRequest

// UpdateServerJSONRequestBody defines body for UpdateServer for application/json ContentType.
type UpdateServerJSONRequestBody = ServerUpdateRequest

// AssociateServerJobJSONRequestBody defines body for AssociateServerJob for application/json ContentType.
type AssociateServerJobJSONRequestBody = ServerJobAssociateRequest

// AssociateServerReleaseJSONRequestBody defines body for AssociateServerRelease for application/json ContentType.
type AssociateServerReleaseJSONRequestBody = ServerReleaseAssociateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List servers
	// (GET /v1/server)
	ListServers(c *gin.Context, params ListServersParams)
	// Create server
	// (POST /v1/server)
	CreateServer(c *gin.Context)
	// Get server by ID
	// (GET /v1/server/{server_id})
	GetServer(c *gin.Context, serverId ServerIDPath)
	// Register agents on an existing server
	// (PUT /v1/server/{server_id})
	UpdateServer(c *gin.Context, serverId ServerIDPath)
	// List automation jobs associated with a server
	// (GET /v1/server/{server_id}/job)
	ListServerJobs(c *gin.Context, serverId ServerIDPath, params ListServerJobsParams)
	// Associate an existing automation job with a server
	// (POST /v1/server/{server_id}/job)
	AssociateServerJob(c *gin.Context, serverId ServerIDPath)
	// Dissociate an automation job from a server
	// (DELETE /v1/server/{server_id}/job/{job_id})
	DissociateServerJob(c *gin.Context, serverId ServerIDPath, jobId JobID, params DissociateServerJobParams)
	// List releases associated with a server
	// (GET /v1/server/{server_id}/release)
	ListServerReleases(c *gin.Context, serverId ServerIDPath, params ListServerReleasesParams)
	// Associate an existing release with a server
	// (POST /v1/server/{server_id}/release)
	AssociateServerRelease(c *gin.Context, serverId ServerIDPath)
	// Dissociate a release from a server
	// (DELETE /v1/server/{server_id}/release/{release_id})
	DissociateServerRelease(c *gin.Context, serverId ServerIDPath, releaseId UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListServers operation middleware
func (siw *ServerInterfaceWrapper) ListServers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "agent_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "agent_id", c.Request.URL.Query(), &params.AgentId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListServers(c, params)
}

// CreateServer operation middleware
func (siw *ServerInterfaceWrapper) CreateServer(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateServer(c)
}

// GetServer operation middleware
func (siw *ServerInterfaceWrapper) GetServer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServer(c, serverId)
}

// UpdateServer operation middleware
func (siw *ServerInterfaceWrapper) UpdateServer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateServer(c, serverId)
}

// ListServerJobs operation middleware
func (siw *ServerInterfaceWrapper) ListServerJobs(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServerJobsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListServerJobs(c, serverId, params)
}

// AssociateServerJob operation middleware
func (siw *ServerInterfaceWrapper) AssociateServerJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AssociateServerJob(c, serverId)
}

// DissociateServerJob operation middleware
func (siw *ServerInterfaceWrapper) DissociateServerJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DissociateServerJobParams

	// ------------- Required query parameter "automation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "automation_id", c.Request.URL.Query(), &params.AutomationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DissociateServerJob(c, serverId, jobId, params)
}

// ListServerReleases operation middleware
func (siw *ServerInterfaceWrapper) ListServerReleases(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServerReleasesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListServerReleases(c, serverId, params)
}

// AssociateServerRelease operation middleware
func (siw *ServerInterfaceWrapper) AssociateServerRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AssociateServerRelease(c, serverId)
}

// DissociateServerRelease operation middleware
func (siw *ServerInterfaceWrapper) DissociateServerRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DissociateServerRelease(c, serverId, releaseId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/server", wrapper.ListServers)
	router.POST(options.BaseURL+"/v1/server", wrapper.CreateServer)
	router.GET(options.BaseURL+"/v1/server/:server_id", wrapper.GetServer)
	router.PUT(options.BaseURL+"/v1/server/:server_id", wrapper.UpdateServer)
	router.GET(options.BaseURL+"/v1/server/:server_id/job", wrapper.ListServerJobs)
	router.POST(options.BaseURL+"/v1/server/:server_id/job", wrapper.AssociateServerJob)
	router.DELETE(options.BaseURL+"/v1/server/:server_id/job/:job_id", wrapper.DissociateServerJob)
	router.GET(options.BaseURL+"/v1/server/:server_id/release", wrapper.ListServerReleases)
	router.POST(options.BaseURL+"/v1/server/:server_id/release", wrapper.AssociateServerRelease)
	router.DELETE(options.BaseURL+"/v1/server/:server_id/release/:release_id", wrapper.DissociateServerRelease)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListServersRequestObject struct {
	Params ListServersParams
}

type ListServersResponseObject interface {
	VisitListServersResponse(w http.ResponseWriter) error
}

type ListServers200JSONResponse ServerListResponse

func (response ListServers200JSONResponse) VisitListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListServers400JSONResponse) VisitListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListServers500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListServers500JSONResponse) VisitListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServerRequestObject struct {
	Body *CreateServerJSONRequestBody
}

type CreateServerResponseObject interface {
	VisitCreateServerResponse(w http.ResponseWriter) error
}

type CreateServer201JSONResponse ServerDataResponse

func (response CreateServer201JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateServer400JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer409JSONResponse struct{ ConflictJSONResponse }

func (response CreateServer409JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateServer500JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetServerRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
}

type GetServerResponseObject interface {
	VisitGetServerResponse(w http.ResponseWriter) error
}

type GetServer200JSONResponse ServerWithRelationsDataResponse

func (response GetServer200JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetServer400JSONResponse struct{ BadRequestJSONResponse }

func (response GetServer400JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetServer404JSONResponse struct{ NotFoundJSONResponse }

func (response GetServer404JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetServer500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetServer500JSONResponse) VisitGetServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServerRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Body     *UpdateServerJSONRequestBody
}

type UpdateServerResponseObject interface {
	VisitUpdateServerResponse(w http.ResponseWriter) error
}

type UpdateServer200JSONResponse ServerWithRelationsDataResponse

func (response UpdateServer200JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateServer400JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateServer404JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateServer409JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateServer500JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerJobsRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Params   ListServerJobsParams
}

type ListServerJobsResponseObject interface {
	VisitListServerJobsResponse(w http.ResponseWriter) error
}

type ListServerJobs200JSONResponse ServerJobListResponse

func (response ListServerJobs200JSONResponse) VisitListServerJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerJobs400JSONResponse struct{ BadRequestJSONResponse }

func (response ListServerJobs400JSONResponse) VisitListServerJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerJobs404JSONResponse struct{ NotFoundJSONResponse }

func (response ListServerJobs404JSONResponse) VisitListServerJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerJobs500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListServerJobs500JSONResponse) VisitListServerJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerJobRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Body     *AssociateServerJobJSONRequestBody
}

type AssociateServerJobResponseObject interface {
	VisitAssociateServerJobResponse(w http.ResponseWriter) error
}

type AssociateServerJob201Response struct {
}

func (response AssociateServerJob201Response) VisitAssociateServerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AssociateServerJob400JSONResponse struct{ BadRequestJSONResponse }

func (response AssociateServerJob400JSONResponse) VisitAssociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerJob404JSONResponse struct{ NotFoundJSONResponse }

func (response AssociateServerJob404JSONResponse) VisitAssociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerJob409JSONResponse struct{ ConflictJSONResponse }

func (response AssociateServerJob409JSONResponse) VisitAssociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerJob500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AssociateServerJob500JSONResponse) VisitAssociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerJobRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	JobId    JobID        `json:"job_id"`
	Params   DissociateServerJobParams
}

type DissociateServerJobResponseObject interface {
	VisitDissociateServerJobResponse(w http.ResponseWriter) error
}

type DissociateServerJob204Response struct {
}

func (response DissociateServerJob204Response) VisitDissociateServerJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DissociateServerJob400JSONResponse struct{ BadRequestJSONResponse }

func (response DissociateServerJob400JSONResponse) VisitDissociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerJob404JSONResponse struct{ NotFoundJSONResponse }

func (response DissociateServerJob404JSONResponse) VisitDissociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerJob500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DissociateServerJob500JSONResponse) VisitDissociateServerJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerReleasesRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Params   ListServerReleasesParams
}

type ListServerReleasesResponseObject interface {
	VisitListServerReleasesResponse(w http.ResponseWriter) error
}

type ListServerReleases200JSONResponse ServerReleaseListResponse

func (response ListServerReleases200JSONResponse) VisitListServerReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerReleases400JSONResponse struct{ BadRequestJSONResponse }

func (response ListServerReleases400JSONResponse) VisitListServerReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerReleases404JSONResponse struct{ NotFoundJSONResponse }

func (response ListServerReleases404JSONResponse) VisitListServerReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListServerReleases500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListServerReleases500JSONResponse) VisitListServerReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerReleaseRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Body     *AssociateServerReleaseJSONRequestBody
}

type AssociateServerReleaseResponseObject interface {
	VisitAssociateServerReleaseResponse(w http.ResponseWriter) error
}

type AssociateServerRelease201Response struct {
}

func (response AssociateServerRelease201Response) VisitAssociateServerReleaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AssociateServerRelease400JSONResponse struct{ BadRequestJSONResponse }

func (response AssociateServerRelease400JSONResponse) VisitAssociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerRelease404JSONResponse struct{ NotFoundJSONResponse }

func (response AssociateServerRelease404JSONResponse) VisitAssociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerRelease409JSONResponse struct{ ConflictJSONResponse }

func (response AssociateServerRelease409JSONResponse) VisitAssociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AssociateServerRelease500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response AssociateServerRelease500JSONResponse) VisitAssociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerReleaseRequestObject struct {
	ServerId  ServerIDPath `json:"server_id"`
	ReleaseId UUID         `json:"release_id"`
}

type DissociateServerReleaseResponseObject interface {
	VisitDissociateServerReleaseResponse(w http.ResponseWriter) error
}

type DissociateServerRelease204Response struct {
}

func (response DissociateServerRelease204Response) VisitDissociateServerReleaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DissociateServerRelease400JSONResponse struct{ BadRequestJSONResponse }

func (response DissociateServerRelease400JSONResponse) VisitDissociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerRelease404JSONResponse struct{ NotFoundJSONResponse }

func (response DissociateServerRelease404JSONResponse) VisitDissociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DissociateServerRelease500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DissociateServerRelease500JSONResponse) VisitDissociateServerReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List servers
	// (GET /v1/server)
	ListServers(ctx context.Context, request ListServersRequestObject) (ListServersResponseObject, error)
	// Create server
	// (POST /v1/server)
	CreateServer(ctx context.Context, request CreateServerRequestObject) (CreateServerResponseObject, error)
	// Get server by ID
	// (GET /v1/server/{server_id})
	GetServer(ctx context.Context, request GetServerRequestObject) (GetServerResponseObject, error)
	// Register agents on an existing server
	// (PUT /v1/server/{server_id})
	UpdateServer(ctx context.Context, request UpdateServerRequestObject) (UpdateServerResponseObject, error)
	// List automation jobs associated with a server
	// (GET /v1/server/{server_id}/job)
	ListServerJobs(ctx context.Context, request ListServerJobsRequestObject) (ListServerJobsResponseObject, error)
	// Associate an existing automation job with a server
	// (POST /v1/server/{server_id}/job)
	AssociateServerJob(ctx context.Context, request AssociateServerJobRequestObject) (AssociateServerJobResponseObject, error)
	// Dissociate an automation job from a server
	// (DELETE /v1/server/{server_id}/job/{job_id})
	DissociateServerJob(ctx context.Context, request DissociateServerJobRequestObject) (DissociateServerJobResponseObject, error)
	// List releases associated with a server
	// (GET /v1/server/{server_id}/release)
	ListServerReleases(ctx context.Context, request ListServerReleasesRequestObject) (ListServerReleasesResponseObject, error)
	// Associate an existing release with a server
	// (POST /v1/server/{server_id}/release)
	AssociateServerRelease(ctx context.Context, request AssociateServerReleaseRequestObject) (AssociateServerReleaseResponseObject, error)
	// Dissociate a release from a server
	// (DELETE /v1/server/{server_id}/release/{release_id})
	DissociateServerRelease(ctx context.Context, request DissociateServerReleaseRequestObject) (DissociateServerReleaseResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListServers operation middleware
func (sh *strictHandler) ListServers(ctx *gin.Context, params ListServersParams) {
	var request ListServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServers(ctx.Request.Context(), request.(ListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServers")
	}

	ctx.Set("operation_id", "ListServers")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListServersResponseObject); ok {
		if err := validResponse.VisitListServersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServer operation middleware
func (sh *strictHandler) CreateServer(ctx *gin.Context) {
	var request CreateServerRequestObject

	var body CreateServerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServer(ctx.Request.Context(), request.(CreateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServer")
	}

	ctx.Set("operation_id", "CreateServer")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateServerResponseObject); ok {
		if err := validResponse.VisitCreateServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetServer operation middleware
func (sh *strictHandler) GetServer(ctx *gin.Context, serverId ServerIDPath) {
	var request GetServerRequestObject

	request.ServerId = serverId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetServer(ctx.Request.Context(), request.(GetServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServer")
	}

	ctx.Set("operation_id", "GetServer")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetServerResponseObject); ok {
		if err := validResponse.VisitGetServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateServer operation middleware
func (sh *strictHandler) UpdateServer(ctx *gin.Context, serverId ServerIDPath) {
	var request UpdateServerRequestObject

	request.ServerId = serverId

	var body UpdateServerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateServer(ctx.Request.Context(), request.(UpdateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateServer")
	}

	ctx.Set("operation_id", "UpdateServer")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateServerResponseObject); ok {
		if err := validResponse.VisitUpdateServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListServerJobs operation middleware
func (sh *strictHandler) ListServerJobs(ctx *gin.Context, serverId ServerIDPath, params ListServerJobsParams) {
	var request ListServerJobsRequestObject

	request.ServerId = serverId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServerJobs(ctx.Request.Context(), request.(ListServerJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServerJobs")
	}

	ctx.Set("operation_id", "ListServerJobs")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListServerJobsResponseObject); ok {
		if err := validResponse.VisitListServerJobsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssociateServerJob operation middleware
func (sh *strictHandler) AssociateServerJob(ctx *gin.Context, serverId ServerIDPath) {
	var request AssociateServerJobRequestObject

	request.ServerId = serverId

	var body AssociateServerJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AssociateServerJob(ctx.Request.Context(), request.(AssociateServerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssociateServerJob")
	}

	ctx.Set("operation_id", "AssociateServerJob")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AssociateServerJobResponseObject); ok {
		if err := validResponse.VisitAssociateServerJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DissociateServerJob operation middleware
func (sh *strictHandler) DissociateServerJob(ctx *gin.Context, serverId ServerIDPath, jobId JobID, params DissociateServerJobParams) {
	var request DissociateServerJobRequestObject

	request.ServerId = serverId
	request.JobId = jobId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DissociateServerJob(ctx.Request.Context(), request.(DissociateServerJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DissociateServerJob")
	}

	ctx.Set("operation_id", "DissociateServerJob")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DissociateServerJobResponseObject); ok {
		if err := validResponse.VisitDissociateServerJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListServerReleases operation middleware
func (sh *strictHandler) ListServerReleases(ctx *gin.Context, serverId ServerIDPath, params ListServerReleasesParams) {
	var request ListServerReleasesRequestObject

	request.ServerId = serverId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListServerReleases(ctx.Request.Context(), request.(ListServerReleasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListServerReleases")
	}

	ctx.Set("operation_id", "ListServerReleases")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListServerReleasesResponseObject); ok {
		if err := validResponse.VisitListServerReleasesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssociateServerRelease operation middleware
func (sh *strictHandler) AssociateServerRelease(ctx *gin.Context, serverId ServerIDPath) {
	var request AssociateServerReleaseRequestObject

	request.ServerId = serverId

	var body AssociateServerReleaseJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AssociateServerRelease(ctx.Request.Context(), request.(AssociateServerReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssociateServerRelease")
	}

	ctx.Set("operation_id", "AssociateServerRelease")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AssociateServerReleaseResponseObject); ok {
		if err := validResponse.VisitAssociateServerReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DissociateServerRelease operation middleware
func (sh *strictHandler) DissociateServerRelease(ctx *gin.Context, serverId ServerIDPath, releaseId UUID) {
	var request DissociateServerReleaseRequestObject

	request.ServerId = serverId
	request.ReleaseId = releaseId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DissociateServerRelease(ctx.Request.Context(), request.(DissociateServerReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DissociateServerRelease")
	}

	ctx.Set("operation_id", "DissociateServerRelease")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DissociateServerReleaseResponseObject); ok {
		if err := validResponse.VisitDissociateServerReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
