// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// Agent defines model for Agent.
type Agent struct {
	Id          UUID           `json:"id"`
	Metadata    ServerMetadata `json:"metadata"`
	Name        string         `json:"name"`
	ServerCount int            `json:"server_count"`
	Type        string         `json:"type"`
	Version     string         `json:"version"`
}

// AgentCreateRequest defines model for AgentCreateRequest.
type AgentCreateRequest struct {
	Metadata *ServerMetadata `json:"metadata,omitempty"`
	Name     string          `json:"name"`
	Type     *string         `json:"type,omitempty"`
	Version  *string         `json:"version,omitempty"`
}

// AgentDataResponse defines model for AgentDataResponse.
type AgentDataResponse struct {
	Data Agent `json:"data"`
}

// AgentDetail defines model for AgentDetail.
type AgentDetail struct {
	Id          UUID           `json:"id"`
	Metadata    ServerMetadata `json:"metadata"`
	Name        string         `json:"name"`
	ServerCount int            `json:"server_count"`
	Servers     []AgentServer  `json:"servers"`
	Type        string         `json:"type"`
	Version     string         `json:"version"`
}

// AgentDetailDataResponse defines model for AgentDetailDataResponse.
type AgentDetailDataResponse struct {
	Data AgentDetail `json:"data"`
}

// AgentListResponse defines model for AgentListResponse.
type AgentListResponse struct {
	Data       []Agent    `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// AgentServer defines model for AgentServer.
type AgentServer struct {
	Hostname string `json:"hostname"`
	Id       UUID   `json:"id"`
}

// AgentServerListResponse defines model for AgentServerListResponse.
type AgentServerListResponse struct {
	Data       []AgentServer `json:"data"`
	Pagination Pagination    `json:"pagination"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// ServerAgentRequest defines model for ServerAgentRequest.
type ServerAgentRequest struct {
	AgentId  *UUID           `json:"agent_id,omitempty"`
	Metadata *ServerMetadata `json:"metadata,omitempty"`
	Name     *string         `json:"name,omitempty"`
	Type     *string         `json:"type,omitempty"`
	Version  *string         `json:"version,omitempty"`
}

// ServerMetadata defines model for ServerMetadata.
type ServerMetadata = map[string]interface{}

// UUID defines model for UUID.
type UUID = uuid.UUID

// AgentIDPath defines model for AgentIDPath.
type AgentIDPath = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// ServerIDPath defines model for ServerIDPath.
type ServerIDPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListGlobalAgentsParams defines parameters for ListGlobalAgents.
type ListGlobalAgentsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Unassigned When true, return only agents not linked to any server
	Unassigned *bool `form:"unassigned,omitempty" json:"unassigned,omitempty"`

	// ServerId Return only agents installed on the given server
	ServerId *UUID `form:"server_id,omitempty" json:"server_id,omitempty"`

	// AgentId Return only the agent with the given ID
	AgentId *UUID `form:"agent_id,omitempty" json:"agent_id,omitempty"`
}

// ListAgentServersParams defines parameters for ListAgentServers.
type ListAgentServersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUnassignedAgentJSONRequestBody defines body for CreateUnassignedAgent for application/json ContentType.
type CreateUnassignedAgentJSONRequestBody = AgentCreateRequest

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = ServerAgentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List agents
	// (GET /v1/agent)
	ListGlobalAgents(c *gin.Context, params ListGlobalAgentsParams)
	// Register an unassigned agent
	// (POST /v1/agent)
	CreateUnassignedAgent(c *gin.Context)
	// Delete an agent and all server links
	// (DELETE /v1/agent/{agent_id})
	DeleteGlobalAgent(c *gin.Context, agentId AgentIDPath)
	// Get agent by ID
	// (GET /v1/agent/{agent_id})
	GetGlobalAgent(c *gin.Context, agentId AgentIDPath)
	// List servers where an agent is installed
	// (GET /v1/agent/{agent_id}/server)
	ListAgentServers(c *gin.Context, agentId AgentIDPath, params ListAgentServersParams)
	// List agents installed on a server
	// (GET /v1/server/{server_id}/agent)
	ListAgents(c *gin.Context, serverId ServerIDPath, params ListAgentsParams)
	// Create or link an agent on a server
	// (POST /v1/server/{server_id}/agent)
	CreateAgent(c *gin.Context, serverId ServerIDPath)
	// Detach an agent from a server
	// (DELETE /v1/server/{server_id}/agent/{agent_id})
	DetachAgent(c *gin.Context, serverId ServerIDPath, agentId AgentIDPath)
	// Get agent by ID
	// (GET /v1/server/{server_id}/agent/{agent_id})
	GetAgent(c *gin.Context, serverId ServerIDPath, agentId AgentIDPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListGlobalAgents operation middleware
func (siw *ServerInterfaceWrapper) ListGlobalAgents(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGlobalAgentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "unassigned" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "unassigned", c.Request.URL.Query(), &params.Unassigned, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter unassigned: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "server_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "server_id", c.Request.URL.Query(), &params.ServerId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "agent_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "agent_id", c.Request.URL.Query(), &params.AgentId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGlobalAgents(c, params)
}

// CreateUnassignedAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateUnassignedAgent(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUnassignedAgent(c)
}

// DeleteGlobalAgent operation middleware
func (siw *ServerInterfaceWrapper) DeleteGlobalAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "agent_id" -------------
	var agentId AgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", c.Param("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteGlobalAgent(c, agentId)
}

// GetGlobalAgent operation middleware
func (siw *ServerInterfaceWrapper) GetGlobalAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "agent_id" -------------
	var agentId AgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", c.Param("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGlobalAgent(c, agentId)
}

// ListAgentServers operation middleware
func (siw *ServerInterfaceWrapper) ListAgentServers(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "agent_id" -------------
	var agentId AgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", c.Param("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentServersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAgentServers(c, agentId, params)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAgents(c, serverId, params)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAgent(c, serverId)
}

// DetachAgent operation middleware
func (siw *ServerInterfaceWrapper) DetachAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "agent_id" -------------
	var agentId AgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", c.Param("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DetachAgent(c, serverId, agentId)
}

// GetAgent operation middleware
func (siw *ServerInterfaceWrapper) GetAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId ServerIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "agent_id" -------------
	var agentId AgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "agent_id", c.Param("agent_id"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAgent(c, serverId, agentId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/agent", wrapper.ListGlobalAgents)
	router.POST(options.BaseURL+"/v1/agent", wrapper.CreateUnassignedAgent)
	router.DELETE(options.BaseURL+"/v1/agent/:agent_id", wrapper.DeleteGlobalAgent)
	router.GET(options.BaseURL+"/v1/agent/:agent_id", wrapper.GetGlobalAgent)
	router.GET(options.BaseURL+"/v1/agent/:agent_id/server", wrapper.ListAgentServers)
	router.GET(options.BaseURL+"/v1/server/:server_id/agent", wrapper.ListAgents)
	router.POST(options.BaseURL+"/v1/server/:server_id/agent", wrapper.CreateAgent)
	router.DELETE(options.BaseURL+"/v1/server/:server_id/agent/:agent_id", wrapper.DetachAgent)
	router.GET(options.BaseURL+"/v1/server/:server_id/agent/:agent_id", wrapper.GetAgent)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListGlobalAgentsRequestObject struct {
	Params ListGlobalAgentsParams
}

type ListGlobalAgentsResponseObject interface {
	VisitListGlobalAgentsResponse(w http.ResponseWriter) error
}

type ListGlobalAgents200JSONResponse AgentListResponse

func (response ListGlobalAgents200JSONResponse) VisitListGlobalAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGlobalAgents400JSONResponse struct{ BadRequestJSONResponse }

func (response ListGlobalAgents400JSONResponse) VisitListGlobalAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListGlobalAgents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListGlobalAgents500JSONResponse) VisitListGlobalAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUnassignedAgentRequestObject struct {
	Body *CreateUnassignedAgentJSONRequestBody
}

type CreateUnassignedAgentResponseObject interface {
	VisitCreateUnassignedAgentResponse(w http.ResponseWriter) error
}

type CreateUnassignedAgent201JSONResponse AgentDataResponse

func (response CreateUnassignedAgent201JSONResponse) VisitCreateUnassignedAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUnassignedAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateUnassignedAgent400JSONResponse) VisitCreateUnassignedAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUnassignedAgent409JSONResponse struct{ ConflictJSONResponse }

func (response CreateUnassignedAgent409JSONResponse) VisitCreateUnassignedAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUnassignedAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateUnassignedAgent500JSONResponse) VisitCreateUnassignedAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGlobalAgentRequestObject struct {
	AgentId AgentIDPath `json:"agent_id"`
}

type DeleteGlobalAgentResponseObject interface {
	VisitDeleteGlobalAgentResponse(w http.ResponseWriter) error
}

type DeleteGlobalAgent204Response struct {
}

func (response DeleteGlobalAgent204Response) VisitDeleteGlobalAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteGlobalAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteGlobalAgent400JSONResponse) VisitDeleteGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGlobalAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteGlobalAgent404JSONResponse) VisitDeleteGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteGlobalAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteGlobalAgent500JSONResponse) VisitDeleteGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetGlobalAgentRequestObject struct {
	AgentId AgentIDPath `json:"agent_id"`
}

type GetGlobalAgentResponseObject interface {
	VisitGetGlobalAgentResponse(w http.ResponseWriter) error
}

type GetGlobalAgent200JSONResponse AgentDetailDataResponse

func (response GetGlobalAgent200JSONResponse) VisitGetGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGlobalAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response GetGlobalAgent400JSONResponse) VisitGetGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetGlobalAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGlobalAgent404JSONResponse) VisitGetGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGlobalAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetGlobalAgent500JSONResponse) VisitGetGlobalAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentServersRequestObject struct {
	AgentId AgentIDPath `json:"agent_id"`
	Params  ListAgentServersParams
}

type ListAgentServersResponseObject interface {
	VisitListAgentServersResponse(w http.ResponseWriter) error
}

type ListAgentServers200JSONResponse AgentServerListResponse

func (response ListAgentServers200JSONResponse) VisitListAgentServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAgentServers400JSONResponse) VisitListAgentServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentServers404JSONResponse struct{ NotFoundJSONResponse }

func (response ListAgentServers404JSONResponse) VisitListAgentServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentServers500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAgentServers500JSONResponse) VisitListAgentServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentsRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Params   ListAgentsParams
}

type ListAgentsResponseObject interface {
	VisitListAgentsResponse(w http.ResponseWriter) error
}

type ListAgents200JSONResponse AgentListResponse

func (response ListAgents200JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAgents400JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents404JSONResponse struct{ NotFoundJSONResponse }

func (response ListAgents404JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAgents500JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	Body     *CreateAgentJSONRequestBody
}

type CreateAgentResponseObject interface {
	VisitCreateAgentResponse(w http.ResponseWriter) error
}

type CreateAgent201JSONResponse AgentDataResponse

func (response CreateAgent201JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAgent400JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateAgent404JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAgent409JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateAgent500JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DetachAgentRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	AgentId  AgentIDPath  `json:"agent_id"`
}

type DetachAgentResponseObject interface {
	VisitDetachAgentResponse(w http.ResponseWriter) error
}

type DetachAgent204Response struct {
}

func (response DetachAgent204Response) VisitDetachAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DetachAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response DetachAgent400JSONResponse) VisitDetachAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DetachAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response DetachAgent404JSONResponse) VisitDetachAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DetachAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DetachAgent500JSONResponse) VisitDetachAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAgentRequestObject struct {
	ServerId ServerIDPath `json:"server_id"`
	AgentId  AgentIDPath  `json:"agent_id"`
}

type GetAgentResponseObject interface {
	VisitGetAgentResponse(w http.ResponseWriter) error
}

type GetAgent200JSONResponse AgentDataResponse

func (response GetAgent200JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAgent400JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAgent404JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgent500JSONResponse) VisitGetAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List agents
	// (GET /v1/agent)
	ListGlobalAgents(ctx context.Context, request ListGlobalAgentsRequestObject) (ListGlobalAgentsResponseObject, error)
	// Register an unassigned agent
	// (POST /v1/agent)
	CreateUnassignedAgent(ctx context.Context, request CreateUnassignedAgentRequestObject) (CreateUnassignedAgentResponseObject, error)
	// Delete an agent and all server links
	// (DELETE /v1/agent/{agent_id})
	DeleteGlobalAgent(ctx context.Context, request DeleteGlobalAgentRequestObject) (DeleteGlobalAgentResponseObject, error)
	// Get agent by ID
	// (GET /v1/agent/{agent_id})
	GetGlobalAgent(ctx context.Context, request GetGlobalAgentRequestObject) (GetGlobalAgentResponseObject, error)
	// List servers where an agent is installed
	// (GET /v1/agent/{agent_id}/server)
	ListAgentServers(ctx context.Context, request ListAgentServersRequestObject) (ListAgentServersResponseObject, error)
	// List agents installed on a server
	// (GET /v1/server/{server_id}/agent)
	ListAgents(ctx context.Context, request ListAgentsRequestObject) (ListAgentsResponseObject, error)
	// Create or link an agent on a server
	// (POST /v1/server/{server_id}/agent)
	CreateAgent(ctx context.Context, request CreateAgentRequestObject) (CreateAgentResponseObject, error)
	// Detach an agent from a server
	// (DELETE /v1/server/{server_id}/agent/{agent_id})
	DetachAgent(ctx context.Context, request DetachAgentRequestObject) (DetachAgentResponseObject, error)
	// Get agent by ID
	// (GET /v1/server/{server_id}/agent/{agent_id})
	GetAgent(ctx context.Context, request GetAgentRequestObject) (GetAgentResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListGlobalAgents operation middleware
func (sh *strictHandler) ListGlobalAgents(ctx *gin.Context, params ListGlobalAgentsParams) {
	var request ListGlobalAgentsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListGlobalAgents(ctx.Request.Context(), request.(ListGlobalAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGlobalAgents")
	}

	ctx.Set("operation_id", "ListGlobalAgents")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListGlobalAgentsResponseObject); ok {
		if err := validResponse.VisitListGlobalAgentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUnassignedAgent operation middleware
func (sh *strictHandler) CreateUnassignedAgent(ctx *gin.Context) {
	var request CreateUnassignedAgentRequestObject

	var body CreateUnassignedAgentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUnassignedAgent(ctx.Request.Context(), request.(CreateUnassignedAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUnassignedAgent")
	}

	ctx.Set("operation_id", "CreateUnassignedAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateUnassignedAgentResponseObject); ok {
		if err := validResponse.VisitCreateUnassignedAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGlobalAgent operation middleware
func (sh *strictHandler) DeleteGlobalAgent(ctx *gin.Context, agentId AgentIDPath) {
	var request DeleteGlobalAgentRequestObject

	request.AgentId = agentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGlobalAgent(ctx.Request.Context(), request.(DeleteGlobalAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGlobalAgent")
	}

	ctx.Set("operation_id", "DeleteGlobalAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteGlobalAgentResponseObject); ok {
		if err := validResponse.VisitDeleteGlobalAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGlobalAgent operation middleware
func (sh *strictHandler) GetGlobalAgent(ctx *gin.Context, agentId AgentIDPath) {
	var request GetGlobalAgentRequestObject

	request.AgentId = agentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGlobalAgent(ctx.Request.Context(), request.(GetGlobalAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGlobalAgent")
	}

	ctx.Set("operation_id", "GetGlobalAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetGlobalAgentResponseObject); ok {
		if err := validResponse.VisitGetGlobalAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAgentServers operation middleware
func (sh *strictHandler) ListAgentServers(ctx *gin.Context, agentId AgentIDPath, params ListAgentServersParams) {
	var request ListAgentServersRequestObject

	request.AgentId = agentId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgentServers(ctx.Request.Context(), request.(ListAgentServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgentServers")
	}

	ctx.Set("operation_id", "ListAgentServers")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAgentServersResponseObject); ok {
		if err := validResponse.VisitListAgentServersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAgents operation middleware
func (sh *strictHandler) ListAgents(ctx *gin.Context, serverId ServerIDPath, params ListAgentsParams) {
	var request ListAgentsRequestObject

	request.ServerId = serverId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgents(ctx.Request.Context(), request.(ListAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgents")
	}

	ctx.Set("operation_id", "ListAgents")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAgentsResponseObject); ok {
		if err := validResponse.VisitListAgentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAgent operation middleware
func (sh *strictHandler) CreateAgent(ctx *gin.Context, serverId ServerIDPath) {
	var request CreateAgentRequestObject

	request.ServerId = serverId

	var body CreateAgentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgent(ctx.Request.Context(), request.(CreateAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgent")
	}

	ctx.Set("operation_id", "CreateAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateAgentResponseObject); ok {
		if err := validResponse.VisitCreateAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DetachAgent operation middleware
func (sh *strictHandler) DetachAgent(ctx *gin.Context, serverId ServerIDPath, agentId AgentIDPath) {
	var request DetachAgentRequestObject

	request.ServerId = serverId
	request.AgentId = agentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DetachAgent(ctx.Request.Context(), request.(DetachAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DetachAgent")
	}

	ctx.Set("operation_id", "DetachAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DetachAgentResponseObject); ok {
		if err := validResponse.VisitDetachAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgent operation middleware
func (sh *strictHandler) GetAgent(ctx *gin.Context, serverId ServerIDPath, agentId AgentIDPath) {
	var request GetAgentRequestObject

	request.ServerId = serverId
	request.AgentId = agentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgent(ctx.Request.Context(), request.(GetAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgent")
	}

	ctx.Set("operation_id", "GetAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAgentResponseObject); ok {
		if err := validResponse.VisitGetAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
