// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// Defines values for JobStatus.
const (
	JobStatusFailed  JobStatus = "failed"
	JobStatusSkipped JobStatus = "skipped"
	JobStatusStarted JobStatus = "started"
	JobStatusSuccess JobStatus = "success"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusFailed:
		return true
	case JobStatusSkipped:
		return true
	case JobStatusStarted:
		return true
	case JobStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ReportType.
const (
	ReportTypeCodeCoverage ReportType = "code_coverage"
	ReportTypeCustom       ReportType = "custom"
	ReportTypeDast         ReportType = "dast"
	ReportTypeSast         ReportType = "sast"
	ReportTypeSbom         ReportType = "sbom"
)

// Valid indicates whether the value is a known member of the ReportType enum.
func (e ReportType) Valid() bool {
	switch e {
	case ReportTypeCodeCoverage:
		return true
	case ReportTypeCustom:
		return true
	case ReportTypeDast:
		return true
	case ReportTypeSast:
		return true
	case ReportTypeSbom:
		return true
	default:
		return false
	}
}

// Defines values for ListReportsGlobalParamsStatus.
const (
	ListReportsGlobalParamsStatusFailed  ListReportsGlobalParamsStatus = "failed"
	ListReportsGlobalParamsStatusSkipped ListReportsGlobalParamsStatus = "skipped"
	ListReportsGlobalParamsStatusStarted ListReportsGlobalParamsStatus = "started"
	ListReportsGlobalParamsStatusSuccess ListReportsGlobalParamsStatus = "success"
)

// Valid indicates whether the value is a known member of the ListReportsGlobalParamsStatus enum.
func (e ListReportsGlobalParamsStatus) Valid() bool {
	switch e {
	case ListReportsGlobalParamsStatusFailed:
		return true
	case ListReportsGlobalParamsStatusSkipped:
		return true
	case ListReportsGlobalParamsStatusStarted:
		return true
	case ListReportsGlobalParamsStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ListReportsGlobalParamsType.
const (
	ListReportsGlobalParamsTypeCodeCoverage ListReportsGlobalParamsType = "code_coverage"
	ListReportsGlobalParamsTypeCustom       ListReportsGlobalParamsType = "custom"
	ListReportsGlobalParamsTypeDast         ListReportsGlobalParamsType = "dast"
	ListReportsGlobalParamsTypeSast         ListReportsGlobalParamsType = "sast"
	ListReportsGlobalParamsTypeSbom         ListReportsGlobalParamsType = "sbom"
)

// Valid indicates whether the value is a known member of the ListReportsGlobalParamsType enum.
func (e ListReportsGlobalParamsType) Valid() bool {
	switch e {
	case ListReportsGlobalParamsTypeCodeCoverage:
		return true
	case ListReportsGlobalParamsTypeCustom:
		return true
	case ListReportsGlobalParamsTypeDast:
		return true
	case ListReportsGlobalParamsTypeSast:
		return true
	case ListReportsGlobalParamsTypeSbom:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Report defines model for Report.
type Report struct {
	Application   string          `json:"application"`
	ApplicationId UUID            `json:"application_id"`
	CreatedAt     time.Time       `json:"created_at"`
	Id            string          `json:"id"`
	Location      *string         `json:"location,omitempty"`
	Metadata      *ReportMetadata `json:"metadata,omitempty"`

	// Output Base64-encoded output. Decoded content is limited to 4 MiB by default.
	Output    *string    `json:"output,omitempty"`
	ReleaseId UUID       `json:"release_id"`
	Status    JobStatus  `json:"status"`
	Type      ReportType `json:"type"`
	Url       *string    `json:"url,omitempty"`
	Version   string     `json:"version"`
}

// ReportCreateRequest defines model for ReportCreateRequest.
type ReportCreateRequest struct {
	Id       string          `json:"id"`
	Location *string         `json:"location,omitempty"`
	Metadata *ReportMetadata `json:"metadata,omitempty"`

	// Output Base64-encoded output. Decoded content is limited to 4 MiB by default.
	Output *string    `json:"output,omitempty"`
	Status JobStatus  `json:"status"`
	Type   ReportType `json:"type"`
	Url    *URL       `json:"url,omitempty"`
}

// ReportDataResponse defines model for ReportDataResponse.
type ReportDataResponse struct {
	Data Report `json:"data"`
}

// ReportListResponse defines model for ReportListResponse.
type ReportListResponse struct {
	Data       []Report   `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// ReportMetadata defines model for ReportMetadata.
type ReportMetadata = map[string]interface{}

// ReportType defines model for ReportType.
type ReportType string

// ReportUpdateRequest defines model for ReportUpdateRequest.
type ReportUpdateRequest struct {
	Metadata *ReportMetadata `json:"metadata,omitempty"`

	// Output Base64-encoded output. Decoded content is limited to 4 MiB by default.
	Output *string   `json:"output,omitempty"`
	Status JobStatus `json:"status"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// ApplicationIDPath defines model for ApplicationIDPath.
type ApplicationIDPath = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// ReleaseIDPath defines model for ReleaseIDPath.
type ReleaseIDPath = openapi_types.UUID

// ReportIDPath defines model for ReportIDPath.
type ReportIDPath = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListReleaseReportsParams defines parameters for ListReleaseReports.
type ListReleaseReportsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListReportsGlobalParams defines parameters for ListReportsGlobal.
type ListReportsGlobalParams struct {
	Page          *Page                          `form:"page,omitempty" json:"page,omitempty"`
	Limit         *Limit                         `form:"limit,omitempty" json:"limit,omitempty"`
	ApplicationId *UUID                          `form:"application_id,omitempty" json:"application_id,omitempty"`
	ReleaseId     *UUID                          `form:"release_id,omitempty" json:"release_id,omitempty"`
	Status        *ListReportsGlobalParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Type          *ListReportsGlobalParamsType   `form:"type,omitempty" json:"type,omitempty"`
}

// ListReportsGlobalParamsStatus defines parameters for ListReportsGlobal.
type ListReportsGlobalParamsStatus string

// ListReportsGlobalParamsType defines parameters for ListReportsGlobal.
type ListReportsGlobalParamsType string

// CreateReleaseReportJSONRequestBody defines body for CreateReleaseReport for application/json ContentType.
type CreateReleaseReportJSONRequestBody = ReportCreateRequest

// UpdateReleaseReportJSONRequestBody defines body for UpdateReleaseReport for application/json ContentType.
type UpdateReleaseReportJSONRequestBody = ReportUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List reports for a release
	// (GET /v1/application/{application_id}/release/{release_id}/report)
	ListReleaseReports(c *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, params ListReleaseReportsParams)
	// Create report for a release
	// (POST /v1/application/{application_id}/release/{release_id}/report)
	CreateReleaseReport(c *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath)
	// Get report by ID
	// (GET /v1/application/{application_id}/release/{release_id}/report/{report_id})
	GetReleaseReport(c *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, reportId ReportIDPath)
	// Update report status
	// (PATCH /v1/application/{application_id}/release/{release_id}/report/{report_id})
	UpdateReleaseReport(c *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, reportId ReportIDPath)
	// List reports across applications
	// (GET /v1/report)
	ListReportsGlobal(c *gin.Context, params ListReportsGlobalParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListReleaseReports operation middleware
func (siw *ServerInterfaceWrapper) ListReleaseReports(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId ReleaseIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReleaseReportsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListReleaseReports(c, applicationId, releaseId, params)
}

// CreateReleaseReport operation middleware
func (siw *ServerInterfaceWrapper) CreateReleaseReport(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId ReleaseIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateReleaseReport(c, applicationId, releaseId)
}

// GetReleaseReport operation middleware
func (siw *ServerInterfaceWrapper) GetReleaseReport(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId ReleaseIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "report_id" -------------
	var reportId ReportIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReleaseReport(c, applicationId, releaseId, reportId)
}

// UpdateReleaseReport operation middleware
func (siw *ServerInterfaceWrapper) UpdateReleaseReport(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId ReleaseIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "report_id" -------------
	var reportId ReportIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "report_id", c.Param("report_id"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter report_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateReleaseReport(c, applicationId, releaseId, reportId)
}

// ListReportsGlobal operation middleware
func (siw *ServerInterfaceWrapper) ListReportsGlobal(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReportsGlobalParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "application_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "application_id", c.Request.URL.Query(), &params.ApplicationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "release_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "release_id", c.Request.URL.Query(), &params.ReleaseId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", c.Request.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListReportsGlobal(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/application/:application_id/release/:release_id/report", wrapper.ListReleaseReports)
	router.POST(options.BaseURL+"/v1/application/:application_id/release/:release_id/report", wrapper.CreateReleaseReport)
	router.GET(options.BaseURL+"/v1/application/:application_id/release/:release_id/report/:report_id", wrapper.GetReleaseReport)
	router.PATCH(options.BaseURL+"/v1/application/:application_id/release/:release_id/report/:report_id", wrapper.UpdateReleaseReport)
	router.GET(options.BaseURL+"/v1/report", wrapper.ListReportsGlobal)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListReleaseReportsRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	ReleaseId     ReleaseIDPath     `json:"release_id"`
	Params        ListReleaseReportsParams
}

type ListReleaseReportsResponseObject interface {
	VisitListReleaseReportsResponse(w http.ResponseWriter) error
}

type ListReleaseReports200JSONResponse ReportListResponse

func (response ListReleaseReports200JSONResponse) VisitListReleaseReportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleaseReports400JSONResponse struct{ BadRequestJSONResponse }

func (response ListReleaseReports400JSONResponse) VisitListReleaseReportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleaseReports401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListReleaseReports401JSONResponse) VisitListReleaseReportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleaseReports404JSONResponse struct{ NotFoundJSONResponse }

func (response ListReleaseReports404JSONResponse) VisitListReleaseReportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleaseReports500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListReleaseReports500JSONResponse) VisitListReleaseReportsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReportRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	ReleaseId     ReleaseIDPath     `json:"release_id"`
	Body          *CreateReleaseReportJSONRequestBody
}

type CreateReleaseReportResponseObject interface {
	VisitCreateReleaseReportResponse(w http.ResponseWriter) error
}

type CreateReleaseReport201JSONResponse ReportDataResponse

func (response CreateReleaseReport201JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReport400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateReleaseReport400JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateReleaseReport401JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReport404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateReleaseReport404JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReport409JSONResponse struct{ ConflictJSONResponse }

func (response CreateReleaseReport409JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseReport500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateReleaseReport500JSONResponse) VisitCreateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseReportRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	ReleaseId     ReleaseIDPath     `json:"release_id"`
	ReportId      ReportIDPath      `json:"report_id"`
}

type GetReleaseReportResponseObject interface {
	VisitGetReleaseReportResponse(w http.ResponseWriter) error
}

type GetReleaseReport200JSONResponse ReportDataResponse

func (response GetReleaseReport200JSONResponse) VisitGetReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GetReleaseReport400JSONResponse) VisitGetReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReleaseReport401JSONResponse) VisitGetReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseReport404JSONResponse struct{ NotFoundJSONResponse }

func (response GetReleaseReport404JSONResponse) VisitGetReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseReport500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetReleaseReport500JSONResponse) VisitGetReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateReleaseReportRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	ReleaseId     ReleaseIDPath     `json:"release_id"`
	ReportId      ReportIDPath      `json:"report_id"`
	Body          *UpdateReleaseReportJSONRequestBody
}

type UpdateReleaseReportResponseObject interface {
	VisitUpdateReleaseReportResponse(w http.ResponseWriter) error
}

type UpdateReleaseReport200JSONResponse ReportDataResponse

func (response UpdateReleaseReport200JSONResponse) VisitUpdateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateReleaseReport400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateReleaseReport400JSONResponse) VisitUpdateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateReleaseReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateReleaseReport401JSONResponse) VisitUpdateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateReleaseReport404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateReleaseReport404JSONResponse) VisitUpdateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateReleaseReport500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateReleaseReport500JSONResponse) VisitUpdateReleaseReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsGlobalRequestObject struct {
	Params ListReportsGlobalParams
}

type ListReportsGlobalResponseObject interface {
	VisitListReportsGlobalResponse(w http.ResponseWriter) error
}

type ListReportsGlobal200JSONResponse ReportListResponse

func (response ListReportsGlobal200JSONResponse) VisitListReportsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsGlobal400JSONResponse struct{ BadRequestJSONResponse }

func (response ListReportsGlobal400JSONResponse) VisitListReportsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsGlobal500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListReportsGlobal500JSONResponse) VisitListReportsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List reports for a release
	// (GET /v1/application/{application_id}/release/{release_id}/report)
	ListReleaseReports(ctx context.Context, request ListReleaseReportsRequestObject) (ListReleaseReportsResponseObject, error)
	// Create report for a release
	// (POST /v1/application/{application_id}/release/{release_id}/report)
	CreateReleaseReport(ctx context.Context, request CreateReleaseReportRequestObject) (CreateReleaseReportResponseObject, error)
	// Get report by ID
	// (GET /v1/application/{application_id}/release/{release_id}/report/{report_id})
	GetReleaseReport(ctx context.Context, request GetReleaseReportRequestObject) (GetReleaseReportResponseObject, error)
	// Update report status
	// (PATCH /v1/application/{application_id}/release/{release_id}/report/{report_id})
	UpdateReleaseReport(ctx context.Context, request UpdateReleaseReportRequestObject) (UpdateReleaseReportResponseObject, error)
	// List reports across applications
	// (GET /v1/report)
	ListReportsGlobal(ctx context.Context, request ListReportsGlobalRequestObject) (ListReportsGlobalResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListReleaseReports operation middleware
func (sh *strictHandler) ListReleaseReports(ctx *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, params ListReleaseReportsParams) {
	var request ListReleaseReportsRequestObject

	request.ApplicationId = applicationId
	request.ReleaseId = releaseId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListReleaseReports(ctx.Request.Context(), request.(ListReleaseReportsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReleaseReports")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListReleaseReportsResponseObject); ok {
		if err := validResponse.VisitListReleaseReportsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateReleaseReport operation middleware
func (sh *strictHandler) CreateReleaseReport(ctx *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath) {
	var request CreateReleaseReportRequestObject

	request.ApplicationId = applicationId
	request.ReleaseId = releaseId

	var body CreateReleaseReportJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateReleaseReport(ctx.Request.Context(), request.(CreateReleaseReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateReleaseReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateReleaseReportResponseObject); ok {
		if err := validResponse.VisitCreateReleaseReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReleaseReport operation middleware
func (sh *strictHandler) GetReleaseReport(ctx *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, reportId ReportIDPath) {
	var request GetReleaseReportRequestObject

	request.ApplicationId = applicationId
	request.ReleaseId = releaseId
	request.ReportId = reportId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReleaseReport(ctx.Request.Context(), request.(GetReleaseReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReleaseReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReleaseReportResponseObject); ok {
		if err := validResponse.VisitGetReleaseReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateReleaseReport operation middleware
func (sh *strictHandler) UpdateReleaseReport(ctx *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath, reportId ReportIDPath) {
	var request UpdateReleaseReportRequestObject

	request.ApplicationId = applicationId
	request.ReleaseId = releaseId
	request.ReportId = reportId

	var body UpdateReleaseReportJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateReleaseReport(ctx.Request.Context(), request.(UpdateReleaseReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateReleaseReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateReleaseReportResponseObject); ok {
		if err := validResponse.VisitUpdateReleaseReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReportsGlobal operation middleware
func (sh *strictHandler) ListReportsGlobal(ctx *gin.Context, params ListReportsGlobalParams) {
	var request ListReportsGlobalRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListReportsGlobal(ctx.Request.Context(), request.(ListReportsGlobalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReportsGlobal")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListReportsGlobalResponseObject); ok {
		if err := validResponse.VisitListReportsGlobalResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
