// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// Defines values for JobStatus.
const (
	Failed  JobStatus = "failed"
	Skipped JobStatus = "skipped"
	Success JobStatus = "success"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Skipped:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Job defines model for Job.
type Job struct {
	Automation   string       `json:"automation"`
	AutomationId UUID         `json:"automation_id"`
	CreatedAt    time.Time    `json:"created_at"`
	Id           string       `json:"id"`
	Location     string       `json:"location"`
	Metadata     *JobMetadata `json:"metadata,omitempty"`

	// Output Base64-encoded output. Decoded content is limited to 4 MiB by default.
	Output   *JobOutput `json:"output,omitempty"`
	Provider string     `json:"provider"`
	Status   JobStatus  `json:"status"`
	Url      URL        `json:"url"`
}

// JobCreateRequest defines model for JobCreateRequest.
type JobCreateRequest struct {
	Id       string       `json:"id"`
	Location string       `json:"location"`
	Metadata *JobMetadata `json:"metadata,omitempty"`

	// Output Base64-encoded output. Decoded content is limited to 4 MiB by default.
	Output *JobOutput `json:"output,omitempty"`
	Status JobStatus  `json:"status"`
	Url    URL        `json:"url"`
}

// JobDataResponse defines model for JobDataResponse.
type JobDataResponse struct {
	Data Job `json:"data"`
}

// JobListResponse defines model for JobListResponse.
type JobListResponse struct {
	Data       []Job      `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// JobMetadata defines model for JobMetadata.
type JobMetadata map[string]interface{}

// JobOutput Base64-encoded output. Decoded content is limited to 4 MiB by default.
type JobOutput = string

// JobStatus defines model for JobStatus.
type JobStatus string

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// AutomationIDPath defines model for AutomationIDPath.
type AutomationIDPath = openapi_types.UUID

// JobID defines model for JobID.
type JobID = string

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListAutomationJobsParams defines parameters for ListAutomationJobs.
type ListAutomationJobsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListJobsGlobalParams defines parameters for ListJobsGlobal.
type ListJobsGlobalParams struct {
	Page         *Page      `form:"page,omitempty" json:"page,omitempty"`
	Limit        *Limit     `form:"limit,omitempty" json:"limit,omitempty"`
	AutomationId *UUID      `form:"automation_id,omitempty" json:"automation_id,omitempty"`
	Status       *JobStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateAutomationJobJSONRequestBody defines body for CreateAutomationJob for application/json ContentType.
type CreateAutomationJobJSONRequestBody = JobCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List jobs for automation
	// (GET /v1/automation/{automation_id}/job)
	ListAutomationJobs(c *gin.Context, automationId AutomationIDPath, params ListAutomationJobsParams)
	// Create job for automation
	// (POST /v1/automation/{automation_id}/job)
	CreateAutomationJob(c *gin.Context, automationId AutomationIDPath)
	// Get job by composite ID
	// (GET /v1/automation/{automation_id}/job/{job_id})
	GetAutomationJob(c *gin.Context, automationId AutomationIDPath, jobId JobID)
	// List jobs across automations
	// (GET /v1/job)
	ListJobsGlobal(c *gin.Context, params ListJobsGlobalParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAutomationJobs operation middleware
func (siw *ServerInterfaceWrapper) ListAutomationJobs(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAutomationJobsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAutomationJobs(c, automationId, params)
}

// CreateAutomationJob operation middleware
func (siw *ServerInterfaceWrapper) CreateAutomationJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAutomationJob(c, automationId)
}

// GetAutomationJob operation middleware
func (siw *ServerInterfaceWrapper) GetAutomationJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "job_id" -------------
	var jobId JobID

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAutomationJob(c, automationId, jobId)
}

// ListJobsGlobal operation middleware
func (siw *ServerInterfaceWrapper) ListJobsGlobal(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsGlobalParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "automation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "automation_id", c.Request.URL.Query(), &params.AutomationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListJobsGlobal(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/automation/:automation_id/job", wrapper.ListAutomationJobs)
	router.POST(options.BaseURL+"/v1/automation/:automation_id/job", wrapper.CreateAutomationJob)
	router.GET(options.BaseURL+"/v1/automation/:automation_id/job/:job_id", wrapper.GetAutomationJob)
	router.GET(options.BaseURL+"/v1/job", wrapper.ListJobsGlobal)
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListAutomationJobsRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
	Params       ListAutomationJobsParams
}

type ListAutomationJobsResponseObject interface {
	VisitListAutomationJobsResponse(w http.ResponseWriter) error
}

type ListAutomationJobs200JSONResponse JobListResponse

func (response ListAutomationJobs200JSONResponse) VisitListAutomationJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAutomationJobs400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAutomationJobs400JSONResponse) VisitListAutomationJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAutomationJobs404JSONResponse struct{ NotFoundJSONResponse }

func (response ListAutomationJobs404JSONResponse) VisitListAutomationJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListAutomationJobs500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAutomationJobs500JSONResponse) VisitListAutomationJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomationJobRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
	Body         *CreateAutomationJobJSONRequestBody
}

type CreateAutomationJobResponseObject interface {
	VisitCreateAutomationJobResponse(w http.ResponseWriter) error
}

type CreateAutomationJob201JSONResponse JobDataResponse

func (response CreateAutomationJob201JSONResponse) VisitCreateAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomationJob400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAutomationJob400JSONResponse) VisitCreateAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomationJob404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateAutomationJob404JSONResponse) VisitCreateAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomationJob500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateAutomationJob500JSONResponse) VisitCreateAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationJobRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
	JobId        JobID            `json:"job_id"`
}

type GetAutomationJobResponseObject interface {
	VisitGetAutomationJobResponse(w http.ResponseWriter) error
}

type GetAutomationJob200JSONResponse JobDataResponse

func (response GetAutomationJob200JSONResponse) VisitGetAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationJob400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAutomationJob400JSONResponse) VisitGetAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationJob404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAutomationJob404JSONResponse) VisitGetAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationJob500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAutomationJob500JSONResponse) VisitGetAutomationJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsGlobalRequestObject struct {
	Params ListJobsGlobalParams
}

type ListJobsGlobalResponseObject interface {
	VisitListJobsGlobalResponse(w http.ResponseWriter) error
}

type ListJobsGlobal200JSONResponse JobListResponse

func (response ListJobsGlobal200JSONResponse) VisitListJobsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsGlobal400JSONResponse struct{ BadRequestJSONResponse }

func (response ListJobsGlobal400JSONResponse) VisitListJobsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListJobsGlobal500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListJobsGlobal500JSONResponse) VisitListJobsGlobalResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List jobs for automation
	// (GET /v1/automation/{automation_id}/job)
	ListAutomationJobs(ctx context.Context, request ListAutomationJobsRequestObject) (ListAutomationJobsResponseObject, error)
	// Create job for automation
	// (POST /v1/automation/{automation_id}/job)
	CreateAutomationJob(ctx context.Context, request CreateAutomationJobRequestObject) (CreateAutomationJobResponseObject, error)
	// Get job by composite ID
	// (GET /v1/automation/{automation_id}/job/{job_id})
	GetAutomationJob(ctx context.Context, request GetAutomationJobRequestObject) (GetAutomationJobResponseObject, error)
	// List jobs across automations
	// (GET /v1/job)
	ListJobsGlobal(ctx context.Context, request ListJobsGlobalRequestObject) (ListJobsGlobalResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListAutomationJobs operation middleware
func (sh *strictHandler) ListAutomationJobs(ctx *gin.Context, automationId AutomationIDPath, params ListAutomationJobsParams) {
	var request ListAutomationJobsRequestObject

	request.AutomationId = automationId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAutomationJobs(ctx.Request.Context(), request.(ListAutomationJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAutomationJobs")
	}

	ctx.Set("operation_id", "ListAutomationJobs")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAutomationJobsResponseObject); ok {
		if err := validResponse.VisitListAutomationJobsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAutomationJob operation middleware
func (sh *strictHandler) CreateAutomationJob(ctx *gin.Context, automationId AutomationIDPath) {
	var request CreateAutomationJobRequestObject

	request.AutomationId = automationId

	var body CreateAutomationJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAutomationJob(ctx.Request.Context(), request.(CreateAutomationJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAutomationJob")
	}

	ctx.Set("operation_id", "CreateAutomationJob")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateAutomationJobResponseObject); ok {
		if err := validResponse.VisitCreateAutomationJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAutomationJob operation middleware
func (sh *strictHandler) GetAutomationJob(ctx *gin.Context, automationId AutomationIDPath, jobId JobID) {
	var request GetAutomationJobRequestObject

	request.AutomationId = automationId
	request.JobId = jobId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAutomationJob(ctx.Request.Context(), request.(GetAutomationJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAutomationJob")
	}

	ctx.Set("operation_id", "GetAutomationJob")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAutomationJobResponseObject); ok {
		if err := validResponse.VisitGetAutomationJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobsGlobal operation middleware
func (sh *strictHandler) ListJobsGlobal(ctx *gin.Context, params ListJobsGlobalParams) {
	var request ListJobsGlobalRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobsGlobal(ctx.Request.Context(), request.(ListJobsGlobalRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobsGlobal")
	}

	ctx.Set("operation_id", "ListJobsGlobal")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListJobsGlobalResponseObject); ok {
		if err := validResponse.VisitListJobsGlobalResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
