// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// Automation defines model for Automation.
type Automation struct {
	CostSavings float64 `json:"cost_savings"`
	Id          UUID    `json:"id"`
	Name        string  `json:"name"`
	Provider    string  `json:"provider"`
	ProviderId  UUID    `json:"provider_id"`
	Url         URL     `json:"url"`
}

// AutomationCreateRequest defines model for AutomationCreateRequest.
type AutomationCreateRequest struct {
	CostSavings *float64 `json:"cost_savings,omitempty"`
	Name        string   `json:"name"`
	ProviderId  UUID     `json:"provider_id"`
	Url         *URL     `json:"url,omitempty"`
}

// AutomationDataResponse defines model for AutomationDataResponse.
type AutomationDataResponse struct {
	Data Automation `json:"data"`
}

// AutomationListResponse defines model for AutomationListResponse.
type AutomationListResponse struct {
	Data       []Automation `json:"data"`
	Pagination Pagination   `json:"pagination"`
}

// AutomationUpdateRequest defines model for AutomationUpdateRequest.
type AutomationUpdateRequest struct {
	CostSavings *float64 `json:"cost_savings,omitempty"`
	Url         *URL     `json:"url,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// AutomationIDPath defines model for AutomationIDPath.
type AutomationIDPath = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListAutomationsParams defines parameters for ListAutomations.
type ListAutomationsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAutomationJSONRequestBody defines body for CreateAutomation for application/json ContentType.
type CreateAutomationJSONRequestBody = AutomationCreateRequest

// UpdateAutomationJSONRequestBody defines body for UpdateAutomation for application/json ContentType.
type UpdateAutomationJSONRequestBody = AutomationUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List automations
	// (GET /v1/automation)
	ListAutomations(c *gin.Context, params ListAutomationsParams)
	// Create automation
	// (POST /v1/automation)
	CreateAutomation(c *gin.Context)
	// Delete automation
	// (DELETE /v1/automation/{automation_id})
	DeleteAutomation(c *gin.Context, automationId AutomationIDPath)
	// Get automation by ID
	// (GET /v1/automation/{automation_id})
	GetAutomation(c *gin.Context, automationId AutomationIDPath)
	// Update automation
	// (PUT /v1/automation/{automation_id})
	UpdateAutomation(c *gin.Context, automationId AutomationIDPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAutomations operation middleware
func (siw *ServerInterfaceWrapper) ListAutomations(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAutomationsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAutomations(c, params)
}

// CreateAutomation operation middleware
func (siw *ServerInterfaceWrapper) CreateAutomation(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAutomation(c)
}

// DeleteAutomation operation middleware
func (siw *ServerInterfaceWrapper) DeleteAutomation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAutomation(c, automationId)
}

// GetAutomation operation middleware
func (siw *ServerInterfaceWrapper) GetAutomation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAutomation(c, automationId)
}

// UpdateAutomation operation middleware
func (siw *ServerInterfaceWrapper) UpdateAutomation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAutomation(c, automationId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/automation", wrapper.ListAutomations)
	router.POST(options.BaseURL+"/v1/automation", wrapper.CreateAutomation)
	router.DELETE(options.BaseURL+"/v1/automation/:automation_id", wrapper.DeleteAutomation)
	router.GET(options.BaseURL+"/v1/automation/:automation_id", wrapper.GetAutomation)
	router.PUT(options.BaseURL+"/v1/automation/:automation_id", wrapper.UpdateAutomation)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListAutomationsRequestObject struct {
	Params ListAutomationsParams
}

type ListAutomationsResponseObject interface {
	VisitListAutomationsResponse(w http.ResponseWriter) error
}

type ListAutomations200JSONResponse AutomationListResponse

func (response ListAutomations200JSONResponse) VisitListAutomationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAutomations400JSONResponse struct{ BadRequestJSONResponse }

func (response ListAutomations400JSONResponse) VisitListAutomationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAutomations500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAutomations500JSONResponse) VisitListAutomationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomationRequestObject struct {
	Body *CreateAutomationJSONRequestBody
}

type CreateAutomationResponseObject interface {
	VisitCreateAutomationResponse(w http.ResponseWriter) error
}

type CreateAutomation201JSONResponse AutomationDataResponse

func (response CreateAutomation201JSONResponse) VisitCreateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateAutomation400JSONResponse) VisitCreateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomation409JSONResponse struct{ ConflictJSONResponse }

func (response CreateAutomation409JSONResponse) VisitCreateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAutomation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateAutomation500JSONResponse) VisitCreateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAutomationRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
}

type DeleteAutomationResponseObject interface {
	VisitDeleteAutomationResponse(w http.ResponseWriter) error
}

type DeleteAutomation204Response struct {
}

func (response DeleteAutomation204Response) VisitDeleteAutomationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAutomation400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteAutomation400JSONResponse) VisitDeleteAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAutomation404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteAutomation404JSONResponse) VisitDeleteAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAutomation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteAutomation500JSONResponse) VisitDeleteAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
}

type GetAutomationResponseObject interface {
	VisitGetAutomationResponse(w http.ResponseWriter) error
}

type GetAutomation200JSONResponse AutomationDataResponse

func (response GetAutomation200JSONResponse) VisitGetAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomation400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAutomation400JSONResponse) VisitGetAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAutomation404JSONResponse) VisitGetAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAutomation500JSONResponse) VisitGetAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAutomationRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
	Body         *UpdateAutomationJSONRequestBody
}

type UpdateAutomationResponseObject interface {
	VisitUpdateAutomationResponse(w http.ResponseWriter) error
}

type UpdateAutomation200JSONResponse AutomationDataResponse

func (response UpdateAutomation200JSONResponse) VisitUpdateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAutomation400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateAutomation400JSONResponse) VisitUpdateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAutomation404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateAutomation404JSONResponse) VisitUpdateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAutomation500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateAutomation500JSONResponse) VisitUpdateAutomationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List automations
	// (GET /v1/automation)
	ListAutomations(ctx context.Context, request ListAutomationsRequestObject) (ListAutomationsResponseObject, error)
	// Create automation
	// (POST /v1/automation)
	CreateAutomation(ctx context.Context, request CreateAutomationRequestObject) (CreateAutomationResponseObject, error)
	// Delete automation
	// (DELETE /v1/automation/{automation_id})
	DeleteAutomation(ctx context.Context, request DeleteAutomationRequestObject) (DeleteAutomationResponseObject, error)
	// Get automation by ID
	// (GET /v1/automation/{automation_id})
	GetAutomation(ctx context.Context, request GetAutomationRequestObject) (GetAutomationResponseObject, error)
	// Update automation
	// (PUT /v1/automation/{automation_id})
	UpdateAutomation(ctx context.Context, request UpdateAutomationRequestObject) (UpdateAutomationResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListAutomations operation middleware
func (sh *strictHandler) ListAutomations(ctx *gin.Context, params ListAutomationsParams) {
	var request ListAutomationsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAutomations(ctx.Request.Context(), request.(ListAutomationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAutomations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListAutomationsResponseObject); ok {
		if err := validResponse.VisitListAutomationsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAutomation operation middleware
func (sh *strictHandler) CreateAutomation(ctx *gin.Context) {
	var request CreateAutomationRequestObject

	var body CreateAutomationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAutomation(ctx.Request.Context(), request.(CreateAutomationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAutomation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateAutomationResponseObject); ok {
		if err := validResponse.VisitCreateAutomationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAutomation operation middleware
func (sh *strictHandler) DeleteAutomation(ctx *gin.Context, automationId AutomationIDPath) {
	var request DeleteAutomationRequestObject

	request.AutomationId = automationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAutomation(ctx.Request.Context(), request.(DeleteAutomationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAutomation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteAutomationResponseObject); ok {
		if err := validResponse.VisitDeleteAutomationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAutomation operation middleware
func (sh *strictHandler) GetAutomation(ctx *gin.Context, automationId AutomationIDPath) {
	var request GetAutomationRequestObject

	request.AutomationId = automationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAutomation(ctx.Request.Context(), request.(GetAutomationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAutomation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAutomationResponseObject); ok {
		if err := validResponse.VisitGetAutomationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAutomation operation middleware
func (sh *strictHandler) UpdateAutomation(ctx *gin.Context, automationId AutomationIDPath) {
	var request UpdateAutomationRequestObject

	request.AutomationId = automationId

	var body UpdateAutomationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAutomation(ctx.Request.Context(), request.(UpdateAutomationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAutomation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateAutomationResponseObject); ok {
		if err := validResponse.VisitUpdateAutomationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
