// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// ComplianceSummary defines model for ComplianceSummary.
type ComplianceSummary struct {
	ByType            []ReportSummary `json:"by_type"`
	FailedReports     int             `json:"failed_reports"`
	StartedReports    int             `json:"started_reports"`
	SuccessRate       float64         `json:"success_rate"`
	SuccessfulReports int             `json:"successful_reports"`
	TotalReports      int             `json:"total_reports"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Release defines model for Release.
type Release struct {
	Application   string    `json:"application"`
	ApplicationId UUID      `json:"application_id"`
	Branch        string    `json:"branch"`
	CommitSha     string    `json:"commit_sha"`
	CreatedAt     time.Time `json:"created_at"`
	Id            UUID      `json:"id"`
	PipelineUrl   URL       `json:"pipeline_url"`
	Version       string    `json:"version"`
}

// ReleaseCreateRequest defines model for ReleaseCreateRequest.
type ReleaseCreateRequest struct {
	Branch      *string `json:"branch,omitempty"`
	CommitSha   *string `json:"commit_sha,omitempty"`
	PipelineUrl *URL    `json:"pipeline_url,omitempty"`
	Version     string  `json:"version"`
}

// ReleaseDataResponse defines model for ReleaseDataResponse.
type ReleaseDataResponse struct {
	Data Release `json:"data"`
}

// ReleaseListItem defines model for ReleaseListItem.
type ReleaseListItem struct {
	Application   string            `json:"application"`
	ApplicationId UUID              `json:"application_id"`
	Branch        string            `json:"branch"`
	CommitSha     string            `json:"commit_sha"`
	Compliance    ComplianceSummary `json:"compliance"`
	CreatedAt     time.Time         `json:"created_at"`
	Id            UUID              `json:"id"`
	PipelineUrl   URL               `json:"pipeline_url"`
	Version       string            `json:"version"`
}

// ReleaseListResponse defines model for ReleaseListResponse.
type ReleaseListResponse struct {
	Data       []ReleaseListItem `json:"data"`
	Pagination Pagination        `json:"pagination"`
}

// ReleaseWithCompliance defines model for ReleaseWithCompliance.
type ReleaseWithCompliance struct {
	Application   string            `json:"application"`
	ApplicationId UUID              `json:"application_id"`
	Branch        string            `json:"branch"`
	CommitSha     string            `json:"commit_sha"`
	Compliance    ComplianceSummary `json:"compliance"`
	CreatedAt     time.Time         `json:"created_at"`
	Id            UUID              `json:"id"`
	PipelineUrl   URL               `json:"pipeline_url"`
	Version       string            `json:"version"`
}

// ReleaseWithComplianceDataResponse defines model for ReleaseWithComplianceDataResponse.
type ReleaseWithComplianceDataResponse struct {
	Data ReleaseWithCompliance `json:"data"`
}

// ReportSummary defines model for ReportSummary.
type ReportSummary struct {
	Count  int    `json:"count"`
	Status string `json:"status"`
	Type   string `json:"type"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// ApplicationIDPath defines model for ApplicationIDPath.
type ApplicationIDPath = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// ReleaseIDPath defines model for ReleaseIDPath.
type ReleaseIDPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListReleasesParams defines parameters for ListReleases.
type ListReleasesParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateReleaseParams defines parameters for CreateRelease.
type CreateReleaseParams struct {
	// Upsert When true, update an existing release with the same version instead of returning a conflict
	Upsert *bool `form:"upsert,omitempty" json:"upsert,omitempty"`
}

// CreateReleaseJSONRequestBody defines body for CreateRelease for application/json ContentType.
type CreateReleaseJSONRequestBody = ReleaseCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List releases for an application
	// (GET /v1/application/{application_id}/release)
	ListReleases(c *gin.Context, applicationId ApplicationIDPath, params ListReleasesParams)
	// Create release for an application
	// (POST /v1/application/{application_id}/release)
	CreateRelease(c *gin.Context, applicationId ApplicationIDPath, params CreateReleaseParams)
	// Get release by ID
	// (GET /v1/application/{application_id}/release/{release_id})
	GetRelease(c *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListReleases operation middleware
func (siw *ServerInterfaceWrapper) ListReleases(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReleasesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListReleases(c, applicationId, params)
}

// CreateRelease operation middleware
func (siw *ServerInterfaceWrapper) CreateRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateReleaseParams

	// ------------- Optional query parameter "upsert" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "upsert", c.Request.URL.Query(), &params.Upsert, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter upsert: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRelease(c, applicationId, params)
}

// GetRelease operation middleware
func (siw *ServerInterfaceWrapper) GetRelease(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "application_id" -------------
	var applicationId ApplicationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "application_id", c.Param("application_id"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter application_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "release_id" -------------
	var releaseId ReleaseIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "release_id", c.Param("release_id"), &releaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter release_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRelease(c, applicationId, releaseId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/application/:application_id/release", wrapper.ListReleases)
	router.POST(options.BaseURL+"/v1/application/:application_id/release", wrapper.CreateRelease)
	router.GET(options.BaseURL+"/v1/application/:application_id/release/:release_id", wrapper.GetRelease)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListReleasesRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	Params        ListReleasesParams
}

type ListReleasesResponseObject interface {
	VisitListReleasesResponse(w http.ResponseWriter) error
}

type ListReleases200JSONResponse ReleaseListResponse

func (response ListReleases200JSONResponse) VisitListReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleases400JSONResponse struct{ BadRequestJSONResponse }

func (response ListReleases400JSONResponse) VisitListReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleases401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListReleases401JSONResponse) VisitListReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleases404JSONResponse struct{ NotFoundJSONResponse }

func (response ListReleases404JSONResponse) VisitListReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListReleases500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListReleases500JSONResponse) VisitListReleasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateReleaseRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	Params        CreateReleaseParams
	Body          *CreateReleaseJSONRequestBody
}

type CreateReleaseResponseObject interface {
	VisitCreateReleaseResponse(w http.ResponseWriter) error
}

type CreateRelease201JSONResponse ReleaseDataResponse

func (response CreateRelease201JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateRelease400JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateRelease401JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateRelease404JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease409JSONResponse struct{ ConflictJSONResponse }

func (response CreateRelease409JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRelease500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateRelease500JSONResponse) VisitCreateReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReleaseRequestObject struct {
	ApplicationId ApplicationIDPath `json:"application_id"`
	ReleaseId     ReleaseIDPath     `json:"release_id"`
}

type GetReleaseResponseObject interface {
	VisitGetReleaseResponse(w http.ResponseWriter) error
}

type GetRelease200JSONResponse ReleaseWithComplianceDataResponse

func (response GetRelease200JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRelease400JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRelease401JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRelease404JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRelease500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetRelease500JSONResponse) VisitGetReleaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List releases for an application
	// (GET /v1/application/{application_id}/release)
	ListReleases(ctx context.Context, request ListReleasesRequestObject) (ListReleasesResponseObject, error)
	// Create release for an application
	// (POST /v1/application/{application_id}/release)
	CreateRelease(ctx context.Context, request CreateReleaseRequestObject) (CreateReleaseResponseObject, error)
	// Get release by ID
	// (GET /v1/application/{application_id}/release/{release_id})
	GetRelease(ctx context.Context, request GetReleaseRequestObject) (GetReleaseResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListReleases operation middleware
func (sh *strictHandler) ListReleases(ctx *gin.Context, applicationId ApplicationIDPath, params ListReleasesParams) {
	var request ListReleasesRequestObject

	request.ApplicationId = applicationId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListReleases(ctx, request.(ListReleasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReleases")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListReleasesResponseObject); ok {
		if err := validResponse.VisitListReleasesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRelease operation middleware
func (sh *strictHandler) CreateRelease(ctx *gin.Context, applicationId ApplicationIDPath, params CreateReleaseParams) {
	var request CreateReleaseRequestObject

	request.ApplicationId = applicationId
	request.Params = params

	var body CreateReleaseJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRelease(ctx, request.(CreateReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateReleaseResponseObject); ok {
		if err := validResponse.VisitCreateReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRelease operation middleware
func (sh *strictHandler) GetRelease(ctx *gin.Context, applicationId ApplicationIDPath, releaseId ReleaseIDPath) {
	var request GetReleaseRequestObject

	request.ApplicationId = applicationId
	request.ReleaseId = releaseId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRelease(ctx, request.(GetReleaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRelease")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReleaseResponseObject); ok {
		if err := validResponse.VisitGetReleaseResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
