// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// AnalyticsAutomationDataResponse defines model for AnalyticsAutomationDataResponse.
type AnalyticsAutomationDataResponse struct {
	Data AutomationAnalytics `json:"data"`
}

// ApplicationComplianceStats defines model for ApplicationComplianceStats.
type ApplicationComplianceStats struct {
	Application       string  `json:"application"`
	ApplicationId     string  `json:"application_id"`
	FailedReports     int     `json:"failed_reports"`
	LatestReleaseId   string  `json:"latest_release_id"`
	LatestVersion     string  `json:"latest_version"`
	StartedReports    int     `json:"started_reports"`
	SuccessRate       float64 `json:"success_rate"`
	SuccessfulReports int     `json:"successful_reports"`
	TotalReports      int     `json:"total_reports"`
}

// AutomationAnalytics defines model for AutomationAnalytics.
type AutomationAnalytics struct {
	ByAutomation     []AutomationJobAnalytics `json:"by_automation"`
	ByLocation       []LocationJobAnalytics   `json:"by_location"`
	FailedJobs       int                      `json:"failed_jobs"`
	StartedJobs      int                      `json:"started_jobs"`
	SuccessRate      float64                  `json:"success_rate"`
	SuccessfulJobs   int                      `json:"successful_jobs"`
	TotalAutomations int                      `json:"total_automations"`
	TotalJobs        int                      `json:"total_jobs"`
}

// AutomationJobAnalytics defines model for AutomationJobAnalytics.
type AutomationJobAnalytics struct {
	Automation     string  `json:"automation"`
	AutomationId   string  `json:"automation_id"`
	FailedJobs     int     `json:"failed_jobs"`
	Provider       string  `json:"provider"`
	StartedJobs    int     `json:"started_jobs"`
	SuccessRate    float64 `json:"success_rate"`
	SuccessfulJobs int     `json:"successful_jobs"`
	TotalJobs      int     `json:"total_jobs"`
}

// ComplianceAnalytics defines model for ComplianceAnalytics.
type ComplianceAnalytics struct {
	ByApplication     []ApplicationComplianceStats `json:"by_application"`
	FailedReports     int                          `json:"failed_reports"`
	StartedReports    int                          `json:"started_reports"`
	SuccessRate       float64                      `json:"success_rate"`
	SuccessfulReports int                          `json:"successful_reports"`
	TotalApplications int                          `json:"total_applications"`
	TotalReleases     int                          `json:"total_releases"`
	TotalReports      int                          `json:"total_reports"`
}

// ComplianceAnalyticsDataResponse defines model for ComplianceAnalyticsDataResponse.
type ComplianceAnalyticsDataResponse struct {
	Data ComplianceAnalytics `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FleetComplianceAnalytics defines model for FleetComplianceAnalytics.
type FleetComplianceAnalytics struct {
	ByLocation            []LocationFleetCompliance `json:"by_location"`
	ComplianceRate        float64                   `json:"compliance_rate"`
	CompliantServers      int                       `json:"compliant_servers"`
	NonCompliantServers   int                       `json:"non_compliant_servers"`
	RequiredAgentCoverage []RequiredAgentCoverage   `json:"required_agent_coverage"`
	TotalRequiredAgents   int                       `json:"total_required_agents"`
	TotalServers          int                       `json:"total_servers"`
}

// FleetComplianceAnalyticsDataResponse defines model for FleetComplianceAnalyticsDataResponse.
type FleetComplianceAnalyticsDataResponse struct {
	Data FleetComplianceAnalytics `json:"data"`
}

// LocationFleetCompliance defines model for LocationFleetCompliance.
type LocationFleetCompliance struct {
	ComplianceRate      float64 `json:"compliance_rate"`
	CompliantServers    int     `json:"compliant_servers"`
	Location            string  `json:"location"`
	NonCompliantServers int     `json:"non_compliant_servers"`
	TotalServers        int     `json:"total_servers"`
}

// LocationJobAnalytics defines model for LocationJobAnalytics.
type LocationJobAnalytics struct {
	FailedJobs     int     `json:"failed_jobs"`
	Location       string  `json:"location"`
	StartedJobs    int     `json:"started_jobs"`
	SuccessRate    float64 `json:"success_rate"`
	SuccessfulJobs int     `json:"successful_jobs"`
	TotalJobs      int     `json:"total_jobs"`
}

// NonCompliantServerListResponse defines model for NonCompliantServerListResponse.
type NonCompliantServerListResponse struct {
	Data       []ServerFleetComplianceDetail `json:"data"`
	Pagination Pagination                    `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// RequiredAgentCoverage defines model for RequiredAgentCoverage.
type RequiredAgentCoverage struct {
	AgentName      string  `json:"agent_name"`
	CoverageRate   float64 `json:"coverage_rate"`
	ServersMissing int     `json:"servers_missing"`
	ServersWith    int     `json:"servers_with"`
}

// ServerFleetComplianceDetail defines model for ServerFleetComplianceDetail.
type ServerFleetComplianceDetail struct {
	Hostname      string   `json:"hostname"`
	Location      string   `json:"location"`
	MissingAgents []string `json:"missing_agents"`
	ServerId      UUID     `json:"server_id"`
}

// UUID defines model for UUID.
type UUID = uuid.UUID

// AutomationIDPath defines model for AutomationIDPath.
type AutomationIDPath = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListNonCompliantServersParams defines parameters for ListNonCompliantServers.
type ListNonCompliantServersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get automation analytics overview
	// (GET /v1/analytics/automation)
	GetAutomationAnalyticsOverview(c *gin.Context)
	// Get analytics overview for one automation
	// (GET /v1/analytics/automation/{automation_id})
	GetAutomationAnalyticsOverviewByID(c *gin.Context, automationId AutomationIDPath)
	// Get compliance analytics overview
	// (GET /v1/analytics/compliance)
	GetComplianceAnalyticsOverview(c *gin.Context)
	// Get fleet compliance analytics overview
	// (GET /v1/analytics/fleet)
	GetFleetComplianceAnalyticsOverview(c *gin.Context)
	// List non-compliant servers
	// (GET /v1/analytics/fleet/non-compliant-servers)
	ListNonCompliantServers(c *gin.Context, params ListNonCompliantServersParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAutomationAnalyticsOverview operation middleware
func (siw *ServerInterfaceWrapper) GetAutomationAnalyticsOverview(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAutomationAnalyticsOverview(c)
}

// GetAutomationAnalyticsOverviewByID operation middleware
func (siw *ServerInterfaceWrapper) GetAutomationAnalyticsOverviewByID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "automation_id" -------------
	var automationId AutomationIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "automation_id", c.Param("automation_id"), &automationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter automation_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAutomationAnalyticsOverviewByID(c, automationId)
}

// GetComplianceAnalyticsOverview operation middleware
func (siw *ServerInterfaceWrapper) GetComplianceAnalyticsOverview(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetComplianceAnalyticsOverview(c)
}

// GetFleetComplianceAnalyticsOverview operation middleware
func (siw *ServerInterfaceWrapper) GetFleetComplianceAnalyticsOverview(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFleetComplianceAnalyticsOverview(c)
}

// ListNonCompliantServers operation middleware
func (siw *ServerInterfaceWrapper) ListNonCompliantServers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNonCompliantServersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListNonCompliantServers(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/analytics/automation", wrapper.GetAutomationAnalyticsOverview)
	router.GET(options.BaseURL+"/v1/analytics/automation/:automation_id", wrapper.GetAutomationAnalyticsOverviewByID)
	router.GET(options.BaseURL+"/v1/analytics/compliance", wrapper.GetComplianceAnalyticsOverview)
	router.GET(options.BaseURL+"/v1/analytics/fleet", wrapper.GetFleetComplianceAnalyticsOverview)
	router.GET(options.BaseURL+"/v1/analytics/fleet/non-compliant-servers", wrapper.ListNonCompliantServers)
}

type BadRequestJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GetAutomationAnalyticsOverviewRequestObject struct {
}

type GetAutomationAnalyticsOverviewResponseObject interface {
	VisitGetAutomationAnalyticsOverviewResponse(w http.ResponseWriter) error
}

type GetAutomationAnalyticsOverview200JSONResponse AnalyticsAutomationDataResponse

func (response GetAutomationAnalyticsOverview200JSONResponse) VisitGetAutomationAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationAnalyticsOverview500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAutomationAnalyticsOverview500JSONResponse) VisitGetAutomationAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationAnalyticsOverviewByIDRequestObject struct {
	AutomationId AutomationIDPath `json:"automation_id"`
}

type GetAutomationAnalyticsOverviewByIDResponseObject interface {
	VisitGetAutomationAnalyticsOverviewByIDResponse(w http.ResponseWriter) error
}

type GetAutomationAnalyticsOverviewByID200JSONResponse AnalyticsAutomationDataResponse

func (response GetAutomationAnalyticsOverviewByID200JSONResponse) VisitGetAutomationAnalyticsOverviewByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationAnalyticsOverviewByID400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAutomationAnalyticsOverviewByID400JSONResponse) VisitGetAutomationAnalyticsOverviewByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationAnalyticsOverviewByID404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAutomationAnalyticsOverviewByID404JSONResponse) VisitGetAutomationAnalyticsOverviewByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAutomationAnalyticsOverviewByID500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAutomationAnalyticsOverviewByID500JSONResponse) VisitGetAutomationAnalyticsOverviewByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetComplianceAnalyticsOverviewRequestObject struct {
}

type GetComplianceAnalyticsOverviewResponseObject interface {
	VisitGetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error
}

type GetComplianceAnalyticsOverview200JSONResponse ComplianceAnalyticsDataResponse

func (response GetComplianceAnalyticsOverview200JSONResponse) VisitGetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetComplianceAnalyticsOverview401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetComplianceAnalyticsOverview401JSONResponse) VisitGetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetComplianceAnalyticsOverview500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetComplianceAnalyticsOverview500JSONResponse) VisitGetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetFleetComplianceAnalyticsOverviewRequestObject struct {
}

type GetFleetComplianceAnalyticsOverviewResponseObject interface {
	VisitGetFleetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error
}

type GetFleetComplianceAnalyticsOverview200JSONResponse FleetComplianceAnalyticsDataResponse

func (response GetFleetComplianceAnalyticsOverview200JSONResponse) VisitGetFleetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFleetComplianceAnalyticsOverview401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetFleetComplianceAnalyticsOverview401JSONResponse) VisitGetFleetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetFleetComplianceAnalyticsOverview500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetFleetComplianceAnalyticsOverview500JSONResponse) VisitGetFleetComplianceAnalyticsOverviewResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListNonCompliantServersRequestObject struct {
	Params ListNonCompliantServersParams
}

type ListNonCompliantServersResponseObject interface {
	VisitListNonCompliantServersResponse(w http.ResponseWriter) error
}

type ListNonCompliantServers200JSONResponse NonCompliantServerListResponse

func (response ListNonCompliantServers200JSONResponse) VisitListNonCompliantServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNonCompliantServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListNonCompliantServers400JSONResponse) VisitListNonCompliantServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListNonCompliantServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListNonCompliantServers401JSONResponse) VisitListNonCompliantServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListNonCompliantServers500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListNonCompliantServers500JSONResponse) VisitListNonCompliantServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get automation analytics overview
	// (GET /v1/analytics/automation)
	GetAutomationAnalyticsOverview(ctx context.Context, request GetAutomationAnalyticsOverviewRequestObject) (GetAutomationAnalyticsOverviewResponseObject, error)
	// Get analytics overview for one automation
	// (GET /v1/analytics/automation/{automation_id})
	GetAutomationAnalyticsOverviewByID(ctx context.Context, request GetAutomationAnalyticsOverviewByIDRequestObject) (GetAutomationAnalyticsOverviewByIDResponseObject, error)
	// Get compliance analytics overview
	// (GET /v1/analytics/compliance)
	GetComplianceAnalyticsOverview(ctx context.Context, request GetComplianceAnalyticsOverviewRequestObject) (GetComplianceAnalyticsOverviewResponseObject, error)
	// Get fleet compliance analytics overview
	// (GET /v1/analytics/fleet)
	GetFleetComplianceAnalyticsOverview(ctx context.Context, request GetFleetComplianceAnalyticsOverviewRequestObject) (GetFleetComplianceAnalyticsOverviewResponseObject, error)
	// List non-compliant servers
	// (GET /v1/analytics/fleet/non-compliant-servers)
	ListNonCompliantServers(ctx context.Context, request ListNonCompliantServersRequestObject) (ListNonCompliantServersResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetAutomationAnalyticsOverview operation middleware
func (sh *strictHandler) GetAutomationAnalyticsOverview(ctx *gin.Context) {
	var request GetAutomationAnalyticsOverviewRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAutomationAnalyticsOverview(ctx.Request.Context(), request.(GetAutomationAnalyticsOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAutomationAnalyticsOverview")
	}

	ctx.Set("operation_id", "GetAutomationAnalyticsOverview")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAutomationAnalyticsOverviewResponseObject); ok {
		if err := validResponse.VisitGetAutomationAnalyticsOverviewResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAutomationAnalyticsOverviewByID operation middleware
func (sh *strictHandler) GetAutomationAnalyticsOverviewByID(ctx *gin.Context, automationId AutomationIDPath) {
	var request GetAutomationAnalyticsOverviewByIDRequestObject

	request.AutomationId = automationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAutomationAnalyticsOverviewByID(ctx.Request.Context(), request.(GetAutomationAnalyticsOverviewByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAutomationAnalyticsOverviewByID")
	}

	ctx.Set("operation_id", "GetAutomationAnalyticsOverviewByID")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAutomationAnalyticsOverviewByIDResponseObject); ok {
		if err := validResponse.VisitGetAutomationAnalyticsOverviewByIDResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetComplianceAnalyticsOverview operation middleware
func (sh *strictHandler) GetComplianceAnalyticsOverview(ctx *gin.Context) {
	var request GetComplianceAnalyticsOverviewRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetComplianceAnalyticsOverview(ctx.Request.Context(), request.(GetComplianceAnalyticsOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetComplianceAnalyticsOverview")
	}

	ctx.Set("operation_id", "GetComplianceAnalyticsOverview")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetComplianceAnalyticsOverviewResponseObject); ok {
		if err := validResponse.VisitGetComplianceAnalyticsOverviewResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFleetComplianceAnalyticsOverview operation middleware
func (sh *strictHandler) GetFleetComplianceAnalyticsOverview(ctx *gin.Context) {
	var request GetFleetComplianceAnalyticsOverviewRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetFleetComplianceAnalyticsOverview(ctx.Request.Context(), request.(GetFleetComplianceAnalyticsOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFleetComplianceAnalyticsOverview")
	}

	ctx.Set("operation_id", "GetFleetComplianceAnalyticsOverview")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetFleetComplianceAnalyticsOverviewResponseObject); ok {
		if err := validResponse.VisitGetFleetComplianceAnalyticsOverviewResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListNonCompliantServers operation middleware
func (sh *strictHandler) ListNonCompliantServers(ctx *gin.Context, params ListNonCompliantServersParams) {
	var request ListNonCompliantServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListNonCompliantServers(ctx.Request.Context(), request.(ListNonCompliantServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNonCompliantServers")
	}

	ctx.Set("operation_id", "ListNonCompliantServers")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListNonCompliantServersResponseObject); ok {
		if err := validResponse.VisitListNonCompliantServersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
