DROP TABLE IF EXISTS api_tokens;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS releases;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS automations;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS users;
