// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Provider defines model for Provider.
type Provider struct {
	Id   UUID   `json:"id"`
	Name string `json:"name"`
	Url  URL    `json:"url"`
}

// ProviderCreateRequest defines model for ProviderCreateRequest.
type ProviderCreateRequest struct {
	Name string `json:"name"`
	Url  URL    `json:"url"`
}

// ProviderDataResponse defines model for ProviderDataResponse.
type ProviderDataResponse struct {
	Data Provider `json:"data"`
}

// ProviderListResponse defines model for ProviderListResponse.
type ProviderListResponse struct {
	Data       []Provider `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = uuid.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// ProviderIDPath defines model for ProviderIDPath.
type ProviderIDPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListProvidersParams defines parameters for ListProviders.
type ListProvidersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateProviderJSONRequestBody defines body for CreateProvider for application/json ContentType.
type CreateProviderJSONRequestBody = ProviderCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List providers
	// (GET /v1/provider)
	ListProviders(c *gin.Context, params ListProvidersParams)
	// Create provider
	// (POST /v1/provider)
	CreateProvider(c *gin.Context)
	// Get provider by ID
	// (GET /v1/provider/{provider_id})
	GetProvider(c *gin.Context, providerId ProviderIDPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProvidersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProviders(c, params)
}

// CreateProvider operation middleware
func (siw *ServerInterfaceWrapper) CreateProvider(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProvider(c)
}

// GetProvider operation middleware
func (siw *ServerInterfaceWrapper) GetProvider(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider_id" -------------
	var providerId ProviderIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "provider_id", c.Param("provider_id"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProvider(c, providerId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/provider", wrapper.ListProviders)
	router.POST(options.BaseURL+"/v1/provider", wrapper.CreateProvider)
	router.GET(options.BaseURL+"/v1/provider/:provider_id", wrapper.GetProvider)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type ListProvidersRequestObject struct {
	Params ListProvidersParams
}

type ListProvidersResponseObject interface {
	VisitListProvidersResponse(w http.ResponseWriter) error
}

type ListProviders200JSONResponse ProviderListResponse

func (response ListProviders200JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProviders400JSONResponse struct{ BadRequestJSONResponse }

func (response ListProviders400JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListProviders500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListProviders500JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProviderRequestObject struct {
	Body *CreateProviderJSONRequestBody
}

type CreateProviderResponseObject interface {
	VisitCreateProviderResponse(w http.ResponseWriter) error
}

type CreateProvider201JSONResponse ProviderDataResponse

func (response CreateProvider201JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProvider400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProvider400JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProvider409JSONResponse struct{ ConflictJSONResponse }

func (response CreateProvider409JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProvider500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateProvider500JSONResponse) VisitCreateProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetProviderRequestObject struct {
	ProviderId ProviderIDPath `json:"provider_id"`
}

type GetProviderResponseObject interface {
	VisitGetProviderResponse(w http.ResponseWriter) error
}

type GetProvider200JSONResponse ProviderDataResponse

func (response GetProvider200JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvider400JSONResponse struct{ BadRequestJSONResponse }

func (response GetProvider400JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvider404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProvider404JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProvider500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetProvider500JSONResponse) VisitGetProviderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List providers
	// (GET /v1/provider)
	ListProviders(ctx context.Context, request ListProvidersRequestObject) (ListProvidersResponseObject, error)
	// Create provider
	// (POST /v1/provider)
	CreateProvider(ctx context.Context, request CreateProviderRequestObject) (CreateProviderResponseObject, error)
	// Get provider by ID
	// (GET /v1/provider/{provider_id})
	GetProvider(ctx context.Context, request GetProviderRequestObject) (GetProviderResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListProviders operation middleware
func (sh *strictHandler) ListProviders(ctx *gin.Context, params ListProvidersParams) {
	var request ListProvidersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProviders(ctx.Request.Context(), request.(ListProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProviders")
	}

	ctx.Set("operation_id", "ListProviders")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProvidersResponseObject); ok {
		if err := validResponse.VisitListProvidersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProvider operation middleware
func (sh *strictHandler) CreateProvider(ctx *gin.Context) {
	var request CreateProviderRequestObject

	var body CreateProviderJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProvider(ctx.Request.Context(), request.(CreateProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProvider")
	}

	ctx.Set("operation_id", "CreateProvider")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateProviderResponseObject); ok {
		if err := validResponse.VisitCreateProviderResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProvider operation middleware
func (sh *strictHandler) GetProvider(ctx *gin.Context, providerId ProviderIDPath) {
	var request GetProviderRequestObject

	request.ProviderId = providerId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProvider(ctx.Request.Context(), request.(GetProviderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProvider")
	}

	ctx.Set("operation_id", "GetProvider")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProviderResponseObject); ok {
		if err := validResponse.VisitGetProviderResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
