// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes    bearerAuthContextKey    = "BearerAuth.Scopes"
	SessionCookieScopes sessionCookieContextKey = "SessionCookie.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// RequiredAgent defines model for RequiredAgent.
type RequiredAgent struct {
	AgentName string `json:"agent_name"`
	AgentType string `json:"agent_type"`
	Id        UUID   `json:"id"`
}

// RequiredAgentCreateRequest defines model for RequiredAgentCreateRequest.
type RequiredAgentCreateRequest struct {
	AgentName string  `json:"agent_name"`
	AgentType *string `json:"agent_type,omitempty"`
}

// RequiredAgentDataResponse defines model for RequiredAgentDataResponse.
type RequiredAgentDataResponse struct {
	Data RequiredAgent `json:"data"`
}

// RequiredAgentListResponse defines model for RequiredAgentListResponse.
type RequiredAgentListResponse struct {
	Data       []RequiredAgent `json:"data"`
	Pagination Pagination      `json:"pagination"`
}

// RequiredAgentUpdateRequest defines model for RequiredAgentUpdateRequest.
type RequiredAgentUpdateRequest struct {
	AgentName *string `json:"agent_name,omitempty"`
	AgentType *string `json:"agent_type,omitempty"`
}

// UUID defines model for UUID.
type UUID = uuid.UUID

// Limit defines model for Limit.
type Limit = int

// Page defines model for Page.
type Page = int

// RequiredAgentIDPath defines model for RequiredAgentIDPath.
type RequiredAgentIDPath = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// sessionCookieContextKey is the context key for SessionCookie security scheme
type sessionCookieContextKey string

// ListRequiredAgentsParams defines parameters for ListRequiredAgents.
type ListRequiredAgentsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateRequiredAgentJSONRequestBody defines body for CreateRequiredAgent for application/json ContentType.
type CreateRequiredAgentJSONRequestBody = RequiredAgentCreateRequest

// UpdateRequiredAgentJSONRequestBody defines body for UpdateRequiredAgent for application/json ContentType.
type UpdateRequiredAgentJSONRequestBody = RequiredAgentUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List required agents
	// (GET /v1/required-agent)
	ListRequiredAgents(c *gin.Context, params ListRequiredAgentsParams)
	// Create a required agent policy
	// (POST /v1/required-agent)
	CreateRequiredAgent(c *gin.Context)
	// Delete a required agent policy
	// (DELETE /v1/required-agent/{required_agent_id})
	DeleteRequiredAgent(c *gin.Context, requiredAgentId RequiredAgentIDPath)
	// Get a required agent policy by ID
	// (GET /v1/required-agent/{required_agent_id})
	GetRequiredAgent(c *gin.Context, requiredAgentId RequiredAgentIDPath)
	// Update a required agent policy
	// (PUT /v1/required-agent/{required_agent_id})
	UpdateRequiredAgent(c *gin.Context, requiredAgentId RequiredAgentIDPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListRequiredAgents operation middleware
func (siw *ServerInterfaceWrapper) ListRequiredAgents(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRequiredAgentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRequiredAgents(c, params)
}

// CreateRequiredAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateRequiredAgent(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRequiredAgent(c)
}

// DeleteRequiredAgent operation middleware
func (siw *ServerInterfaceWrapper) DeleteRequiredAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "required_agent_id" -------------
	var requiredAgentId RequiredAgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "required_agent_id", c.Param("required_agent_id"), &requiredAgentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter required_agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRequiredAgent(c, requiredAgentId)
}

// GetRequiredAgent operation middleware
func (siw *ServerInterfaceWrapper) GetRequiredAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "required_agent_id" -------------
	var requiredAgentId RequiredAgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "required_agent_id", c.Param("required_agent_id"), &requiredAgentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter required_agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRequiredAgent(c, requiredAgentId)
}

// UpdateRequiredAgent operation middleware
func (siw *ServerInterfaceWrapper) UpdateRequiredAgent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "required_agent_id" -------------
	var requiredAgentId RequiredAgentIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "required_agent_id", c.Param("required_agent_id"), &requiredAgentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter required_agent_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(SessionCookieScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRequiredAgent(c, requiredAgentId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/required-agent", wrapper.ListRequiredAgents)
	router.POST(options.BaseURL+"/v1/required-agent", wrapper.CreateRequiredAgent)
	router.DELETE(options.BaseURL+"/v1/required-agent/:required_agent_id", wrapper.DeleteRequiredAgent)
	router.GET(options.BaseURL+"/v1/required-agent/:required_agent_id", wrapper.GetRequiredAgent)
	router.PUT(options.BaseURL+"/v1/required-agent/:required_agent_id", wrapper.UpdateRequiredAgent)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type InternalServerErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListRequiredAgentsRequestObject struct {
	Params ListRequiredAgentsParams
}

type ListRequiredAgentsResponseObject interface {
	VisitListRequiredAgentsResponse(w http.ResponseWriter) error
}

type ListRequiredAgents200JSONResponse RequiredAgentListResponse

func (response ListRequiredAgents200JSONResponse) VisitListRequiredAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequiredAgents400JSONResponse struct{ BadRequestJSONResponse }

func (response ListRequiredAgents400JSONResponse) VisitListRequiredAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequiredAgents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListRequiredAgents401JSONResponse) VisitListRequiredAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequiredAgents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListRequiredAgents500JSONResponse) VisitListRequiredAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRequiredAgentRequestObject struct {
	Body *CreateRequiredAgentJSONRequestBody
}

type CreateRequiredAgentResponseObject interface {
	VisitCreateRequiredAgentResponse(w http.ResponseWriter) error
}

type CreateRequiredAgent201JSONResponse RequiredAgentDataResponse

func (response CreateRequiredAgent201JSONResponse) VisitCreateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRequiredAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateRequiredAgent400JSONResponse) VisitCreateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRequiredAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateRequiredAgent401JSONResponse) VisitCreateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRequiredAgent409JSONResponse struct{ ConflictJSONResponse }

func (response CreateRequiredAgent409JSONResponse) VisitCreateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateRequiredAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateRequiredAgent500JSONResponse) VisitCreateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRequiredAgentRequestObject struct {
	RequiredAgentId RequiredAgentIDPath `json:"required_agent_id"`
}

type DeleteRequiredAgentResponseObject interface {
	VisitDeleteRequiredAgentResponse(w http.ResponseWriter) error
}

type DeleteRequiredAgent204Response struct {
}

func (response DeleteRequiredAgent204Response) VisitDeleteRequiredAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteRequiredAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteRequiredAgent401JSONResponse) VisitDeleteRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRequiredAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteRequiredAgent404JSONResponse) VisitDeleteRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteRequiredAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteRequiredAgent500JSONResponse) VisitDeleteRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequiredAgentRequestObject struct {
	RequiredAgentId RequiredAgentIDPath `json:"required_agent_id"`
}

type GetRequiredAgentResponseObject interface {
	VisitGetRequiredAgentResponse(w http.ResponseWriter) error
}

type GetRequiredAgent200JSONResponse RequiredAgentDataResponse

func (response GetRequiredAgent200JSONResponse) VisitGetRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequiredAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRequiredAgent401JSONResponse) VisitGetRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequiredAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRequiredAgent404JSONResponse) VisitGetRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequiredAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetRequiredAgent500JSONResponse) VisitGetRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgentRequestObject struct {
	RequiredAgentId RequiredAgentIDPath `json:"required_agent_id"`
	Body            *UpdateRequiredAgentJSONRequestBody
}

type UpdateRequiredAgentResponseObject interface {
	VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error
}

type UpdateRequiredAgent200JSONResponse RequiredAgentDataResponse

func (response UpdateRequiredAgent200JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateRequiredAgent400JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateRequiredAgent401JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgent404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateRequiredAgent404JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgent409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateRequiredAgent409JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateRequiredAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateRequiredAgent500JSONResponse) VisitUpdateRequiredAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List required agents
	// (GET /v1/required-agent)
	ListRequiredAgents(ctx context.Context, request ListRequiredAgentsRequestObject) (ListRequiredAgentsResponseObject, error)
	// Create a required agent policy
	// (POST /v1/required-agent)
	CreateRequiredAgent(ctx context.Context, request CreateRequiredAgentRequestObject) (CreateRequiredAgentResponseObject, error)
	// Delete a required agent policy
	// (DELETE /v1/required-agent/{required_agent_id})
	DeleteRequiredAgent(ctx context.Context, request DeleteRequiredAgentRequestObject) (DeleteRequiredAgentResponseObject, error)
	// Get a required agent policy by ID
	// (GET /v1/required-agent/{required_agent_id})
	GetRequiredAgent(ctx context.Context, request GetRequiredAgentRequestObject) (GetRequiredAgentResponseObject, error)
	// Update a required agent policy
	// (PUT /v1/required-agent/{required_agent_id})
	UpdateRequiredAgent(ctx context.Context, request UpdateRequiredAgentRequestObject) (UpdateRequiredAgentResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func defaultStrictGinRequestErrorHandler(ctx *gin.Context, err error) {
	if _, ok := err.(*http.MaxBytesError); ok {
		ctx.JSON(http.StatusRequestEntityTooLarge, gin.H{"error": "request body too large"})
		return
	}
	ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: defaultStrictGinRequestErrorHandler,
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = defaultStrictGinRequestErrorHandler
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"error": http.StatusText(http.StatusInternalServerError)})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListRequiredAgents operation middleware
func (sh *strictHandler) ListRequiredAgents(ctx *gin.Context, params ListRequiredAgentsParams) {
	var request ListRequiredAgentsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRequiredAgents(ctx.Request.Context(), request.(ListRequiredAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRequiredAgents")
	}

	ctx.Set("operation_id", "ListRequiredAgents")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListRequiredAgentsResponseObject); ok {
		if err := validResponse.VisitListRequiredAgentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateRequiredAgent operation middleware
func (sh *strictHandler) CreateRequiredAgent(ctx *gin.Context) {
	var request CreateRequiredAgentRequestObject

	var body CreateRequiredAgentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRequiredAgent(ctx.Request.Context(), request.(CreateRequiredAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRequiredAgent")
	}

	ctx.Set("operation_id", "CreateRequiredAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateRequiredAgentResponseObject); ok {
		if err := validResponse.VisitCreateRequiredAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteRequiredAgent operation middleware
func (sh *strictHandler) DeleteRequiredAgent(ctx *gin.Context, requiredAgentId RequiredAgentIDPath) {
	var request DeleteRequiredAgentRequestObject

	request.RequiredAgentId = requiredAgentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteRequiredAgent(ctx.Request.Context(), request.(DeleteRequiredAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteRequiredAgent")
	}

	ctx.Set("operation_id", "DeleteRequiredAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteRequiredAgentResponseObject); ok {
		if err := validResponse.VisitDeleteRequiredAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRequiredAgent operation middleware
func (sh *strictHandler) GetRequiredAgent(ctx *gin.Context, requiredAgentId RequiredAgentIDPath) {
	var request GetRequiredAgentRequestObject

	request.RequiredAgentId = requiredAgentId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRequiredAgent(ctx.Request.Context(), request.(GetRequiredAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRequiredAgent")
	}

	ctx.Set("operation_id", "GetRequiredAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRequiredAgentResponseObject); ok {
		if err := validResponse.VisitGetRequiredAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateRequiredAgent operation middleware
func (sh *strictHandler) UpdateRequiredAgent(ctx *gin.Context, requiredAgentId RequiredAgentIDPath) {
	var request UpdateRequiredAgentRequestObject

	request.RequiredAgentId = requiredAgentId

	var body UpdateRequiredAgentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateRequiredAgent(ctx.Request.Context(), request.(UpdateRequiredAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateRequiredAgent")
	}

	ctx.Set("operation_id", "UpdateRequiredAgent")

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateRequiredAgentResponseObject); ok {
		if err := validResponse.VisitUpdateRequiredAgentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
